### ISSUE TITLE
a main feature of the mod is completely broken

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#10]
And another one: Basically everything concerning energy storage and batteries is broken, i cant even describe this... the textures are broken, and there's even energy duplication

i may be able to stream it to you if you had discord so i could go a little more in-depth

**Comment by Drillgon200** [comment]
It's probable I've already fixed this.

**Comment by TheForge129** [comment]
> It's probable I've already fixed this.

Ah, makes sense
