### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by elilouve** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#102]
Hi, so first, I'm not english so sorry for the mistakes.

As you will see in the screenshots, it seems that the fluid identifier part is missings. 
I notice this error on all machines that use fluid identifier. Some of them can dispaly an explanation tooltip but the box is still missings.
The use of infinite barrel is impossible for exemple, which very inconvenient. 
Here's hoping useful to you.

My game
![2021-06-08 00_49_09-Minecraft 1 12 2](https://user-images.githubusercontent.com/85528438/121097874-06353f80-c7f5-11eb-8713-548e0a5d2418.png)

A Youtube video for comparison
![2021-06-08 00_49_54-(65) How to make a _DFC Reactor_ in HBMs Mod _ DARK FUSION CORE Reactor Tutorial](https://user-images.githubusercontent.com/85528438/121097878-07ff0300-c7f5-11eb-9c57-baa5ed81a50d.png)

Ps: I use the 1.4.4A version.

**Comment by TheForge129** [comment]
that's intentional iirc, i already pointed out the issue with the infinite
barrel in a previous issue

**Comment by elilouve** [comment]
> that's intentional iirc, i already pointed out the issue with the infinite
> barrel in a previous issue
> 

Ho Okey
I had not seen despite my research. when in doubt I would leave this ticket open in case it is useful since it concerns any machine.

**Comment by Drillgon200** [comment]
1.12 doesn't use fluid identifiers for most machines, I deemed them unnecessary. To use the infinite barrel, fill it partly with the fluid you want then put the barrel there.
