### ISSUE TITLE
Crash after blowing up a nuclear bomb

### ISSUE THREAD

**Issue by Nici660** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#105]
So I blowed up a nuclear bomb and after flying around for a bit the Game crashed (several times) with 
this issue:
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[oak, spruce, birch, jungle]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
and this:
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[acacia, dark_oak]} as it does not exist in BlockStateContainer{block=minecraft:red_mushroom_block, properties=[variant]}
and this:
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[acacia, dark_oak]} as it does not exist in BlockStateContainer{block=minecraft:fire, properties=[age, east, north, south, up, west]}
and this 
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[acacia, dark_oak]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

First this happend in my main world, with several mods, but then I tested it again in a world with only hbm and it crashed again.
It is not to bad but it is still annoying
In my opinion, it has to do something with the charred log cause only this is created from all the blocks, that are listed above, in a nuclear explosion.
Note: You have to fly or walk around a bit: about 3 to 15 minutes

**Comment by Drillgon200** [comment]
That doesn't really tell me where the error is, I need a full log.

**Comment by Nici660** [comment]
Here is the complete log of the world with only hbm:
[crash-2021-06-13_08.15.54-server.txt](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/6650480/crash-2021-06-13_08.15.54-server.txt)

**Comment by Drillgon200** [comment]
I don't see a reference to NTM in that stack trace, and I also don't see the code that references BlockOldLeaf in BlockLeaves#getDrops. Try updating your forge, the latest is 2855 and you have 2847.
