### ISSUE TITLE
Random Satellite Bombings?

### ISSUE THREAD

**Issue by SadManAAA** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#106]
Yeah chief, don't know what to say on this one. Its just random.

![image](https://user-images.githubusercontent.com/56691786/121860672-2344a380-cd0a-11eb-8355-963c56ef0adf.png)

![image](https://user-images.githubusercontent.com/56691786/121860698-29d31b00-cd0a-11eb-8dd5-5c0c4f6600b7.png)

**Comment by Drillgon200** [comment]
Did you happen to turn on cataclysm mode in the config?

**Comment by SadManAAA** [comment]
> Did you happen to turn on cataclysm mode in the config?

Ah thanks, turns out someone turned it on for the bloody server and promptly lost us three bases. 

I apologize for wasting your time, I should've been more vigilant.
