### ISSUE TITLE
Dark Crystal not working properly

### ISSUE THREAD

**Issue by Fur-Politician** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#107]
Hi well ,I crafted the Dark Crystal secret block for seeing the world burn ,but It doesn't do anything more than harden ,it doesn't expand ,and you can break it with an iron pickaxe ...(I'm using the 1.4.4.a that I downloaded from forge because I'm in a server of aternos and that's the only version that accepts)

**Comment by Drillgon200** [comment]
Did you enable virus blocks first in the config?

**Comment by Fur-Politician** [comment]
Uhhh sorry I don't know how to do that...can you tell me how?

**Comment by Fur-Politician** [comment]
Oh forget I just discovered how XD sorry for bothering
