### ISSUE TITLE
Extra Utilities compatibility problem

### ISSUE THREAD

**Issue by abel1502** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#108]
Apparently, world generation in the Deep Dark, a new dimension provided by Extra Utilities, attempts to generate HBM's structures, which fails for some reason. 

[crash-2021-06-15_23.33.57-server.txt](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/6658611/crash-2021-06-15_23.33.57-server.txt)

This seems to be the responsible code:

https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/blob/9e1be111f537fdf07dc898dec246c53885a0722b/src/main/java/com/hbm/lib/HbmWorldGen.java#L388-L435

I assume the problem is that the y coordinate is over the build limit, as Deep Dark is a cave-like dimension, and so no vauld block nor its tile entity are created. Probably needs an extra check for that here and in the rest of the structure generation, or, a quicker but dirtier solution, you could just verify that you are in the overworld in the beginning of the generation method

**Comment by Drillgon200** [comment]
Verifying in the overworld is not a solution, NTM structures are supposed to generate in other dimensions.

**Comment by Drillgon200** [comment]
I think that's fixed anyway, I'll have to see if any of the other structures are broken later.
