### ISSUE TITLE
Geysers

### ISSUE THREAD

**Issue by TrojanHorseForSale** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#109]
So I have some questions about the mod's mechanics.

Do you have a discord or email I can talk to you about?

**Comment by Drillgon200** [comment]
You can talk here about that. My discord tag is also listed on this github.

**Comment by TrojanHorseForSale** [comment]
> You can talk here about that. My discord tag is also listed on this github.

I can't find it, what is your Tag? (sorry I'm new here)

**Comment by Drillgon200** [comment]
It's probably better if you ask your questions here, that way people will be able to find the answers through a google search. My discord tag is Drillgon200#0288.
