### ISSUE TITLE
Crash with Nukepowered Utils mod

### ISSUE THREAD

**Issue by whatsapp2** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#11]
**Mod List:**

forge-1.12.2-14.23.5.2847
NPUtils-1.12.2-1.3.21
gregtech-1.12.2-1.9.3.531
CodeChickenLib-1.12.2-3.2.3.357-universal
hbm-1.3.5A-1.12.2 [Latest In-Dev Version]

**Crash Report:**
https://pastebin.com/xMsvnXWS

**Observations:**
There is no crash with hbm-1.3.4a-1.12.2. An issue was also created in Nukepowered Utils Github

**Comment by Drillgon200** [comment]
Well, I hope their dev can figure out what's causing it, because NTM isn't even in that crash report's stack trace.
