### ISSUE TITLE
Discord/Email

### ISSUE THREAD

**Issue by TrojanHorseForSale** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#110]
What is your Discord tag and or email?

Sorry I am new on this site

**Comment by Drillgon200** [comment]
My discord is listed on the main page and I also told you on your previous issue. In case you missed it, I also said that it's probably better if you ask questions here because that means they'll show up for other people using google.

**Comment by TrojanHorseForSale** [comment]
> My discord is listed on the main page and I also told you on your previous issue. In case you missed it, I also said that it's probably better if you ask questions here because that means they'll show up for other people using google.

I am blind but where is it listed on the main page?

**Comment by Drillgon200** [comment]
![image](https://user-images.githubusercontent.com/50186362/122425905-af420f80-cf44-11eb-91f4-a367bc42ec81.png)
