### ISSUE TITLE
Doesn't work for athernos 

### ISSUE THREAD

**Issue by ChuvirlaX** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#112]
Hello, please tell me what to do if I get an error when I go to the server athenos ?

**Comment by Drillgon200** [comment]
That's not very helpful, I need more information. What kind of error is it, and can you give me a log?

**Comment by ChuvirlaX** [comment]
Here are the Log  https://mclo.gs/lFUhXHt Sorry for my bad english

**Comment by ChuvirlaX** [comment]
The server just stops and writes an error

**Comment by ChuvirlaX** [comment]
The server just stops and writes "Error"

**Comment by abel1502** [comment]
The problem seems to be with the "rtm" mod, not this one.

https://mclo.gs/lFUhXHt#L14746

**Comment by ChuvirlaX** [comment]
Well, there was no such problem before, it appeared when I installed HBM

**Comment by ChuvirlaX** [comment]
Thank you ! It really was in RTM, I installed Immersive Railroading and I no longer have an error!
