### ISSUE TITLE
How do I fuel the glide jetpack?

### ISSUE THREAD

**Issue by Joey-Destroyah** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#113]

**Comment by UFFR** [comment]
The same way you would any other NTM fluid tank.

-- 
UFFR

**Comment by Drillgon200** [comment]
Fill it in a tank with kerosene, nitan, or bf rocket fuel.

**Comment by Joey-Destroyah** [comment]
Thanks for the help!
