### ISSUE TITLE
Game crashes when getting the paa armor

### ISSUE THREAD

**Issue by vesko128** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#117]
When you put on the PaA Chest Protection Plate, the PaA Leg Reinforcements and the PaA "good ol' shoes", the game crashes
log:
[crash-2021-07-10_12.33.54-client.txt](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/6795009/crash-2021-07-10_12.33.54-client.txt)

**Comment by Drillgon200** [comment]
Fixed, I don't remember when.
