### ISSUE TITLE
Question about Meteor Dungeon

### ISSUE THREAD

**Issue by Nici660** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#118]
I only habe a question about the Meteor Dungeons. Do they already spawn or are they a work in process? Cause i changed the config a bit to make them spawn way more often (about 1 per 1000 chunk, to see them). But i couldn‘t find any Even with a x-ray mod.

**Comment by TheForge129** [comment]
They spawn, I got a lucky one within 500 blocks of spawn and next to my
base. I can send a screenshot of you want

**Comment by Nici660** [comment]
No you don‘t have to, it is just that I’am a bit confused, cause I set the config number so high that it should be easy to find one of them. Is the config don‘t working or did I do something wrong?

**Comment by Drillgon200** [comment]
There really is a bug with this, that will be fixed in the next update. The dungeon generation code was accidentally placed inside the safe generation code, so the actual probability is safe probability times dungeon probability.
