### ISSUE TITLE
not compatible with the optifine

### ISSUE THREAD

**Issue by Rezanands** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#123]
when you start the world, with the optifine installed, minecraft freezes forever, until you re-enter the game

**Comment by TheForge129** [comment]
i've played with optifine on the newest ver tho

**Comment by ghost** [comment]
Can confirm that this does not work with Optifine.

**Comment by TheForge129** [comment]
try disabling shaders in the config

**Comment by SheldonCurtiss** [comment]
Also doesn't work with optifine.
Testing with the shader config change now.

**Comment by SheldonCurtiss** [comment]
It fixed it

**Comment by elzurddo** [comment]
How do you fix the problem? I had shaders working an all of the sudden it doesn't work.

**Comment by SheldonCurtiss** [comment]
> How do you fix the problem? I had shaders working an all of the sudden it doesn't work.

    B:1.25_instancedParticles=false

    B:1.29_enableShaders2=false

Pretty sure the second one is what fixes it but it says the first setting is incompatible with shaders so I disabled that too

**Comment by SheldonCurtiss** [comment]
@elzurddo

**Comment by Drillgon200** [comment]
I'm pretty sure it's the optifine fast render option causing the incompatibility.
