### ISSUE TITLE
 proposal

### ISSUE THREAD

**Issue by xingchengs** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#125]
Can you add an adaptation to crafttweaker [1.12.2]?
This is a great mod, but it lacks some flexibility!

**Comment by Drillgon200** [comment]
I am no longer adding features to this mod, only fixing issues.
Most of the NTM machine recipes are very static and couldn't easily be made configurable. What would you have liked craft tweaker to do?

**Comment by gatoborrachon** [comment]
i guess he meant to add/remove recipes in the many machines that NTM has (the Centrifuges, Chemical Plant, Ore Acidizer, Blast Furnace, etc)

in case of the Assembler, there's already a config file inside `/.minecraft/config/hbm/assemblerConfig.cfg` where you can tweak Assembler recipes

but if you really want to tweak the recipes, fork the mod and change them,

**Comment by xingchengs** [comment]
crafttweaker is a very useful tool for integrated package makers like me, it can quickly write recipes to achieve goals! But you didn’t add this part to it, I’m sorry

In order to prevent semantic errors, the following is the original text. Because I have insufficient English proficiency, I basically rely on translation software for communication:
crafttweaker对于像我这样的整合包制作者来说是一个非常有用的工具，它可以快速编写实现目标的配方！但是您并不对其添加这部分内容，我表示很遗憾
