### ISSUE TITLE
R.I.P Drillgon B.M

### ISSUE THREAD

**Issue by Joey-Destroyah** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#126]
2018-2021

I dont know why it got canceled, but as a wise man one said,
"Don't cry because it's over, smile because it happened."
--Dr. Seuss

**Comment by Joey-Destroyah** [comment]
BTW. I will keep this thread open indefinitely or on the extremely low chance that @Drillgon continues developing new features.
But at least he is making new bug fixes.

**Comment by Joey-Destroyah** [comment]
Update: it appears he is still making mods, but a lot slower.

**Comment by HbmMods** [comment]
bruh
