### ISSUE TITLE
get this mod attention that it deserved to has

### ISSUE THREAD

**Issue by blablase** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#132]
by looking at how realistic this mod look and by giving it a more realistic engine like the one we see on teardown, then getting featured on asianhalfsquat channel, people would craze for it or so i thought on a 2nd most popular version and the trend of realistic engine

**Comment by Joey-Destroyah** [comment]
Unfortunately, Drillgon stopped updating the mod. He will still be doing bug fixes, though.

**Comment by HbmMods** [comment]
bruh

**Comment by Drillgon200** [comment]
Ah yes, let me just go rewrite the entire minecraft engine in a way that is more robust than teardown, a game with some of the most advanced destruction physics available written by someone with way more experience than me, and works on the much larger scale of a minecraft world, while keeping it compatible with regular mods. Even if I was still working on features for this port, this is massively infeasible.
