### ISSUE TITLE
Game crashed when I put down the Blast Door

### ISSUE THREAD

**Issue by sdddddf80** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#133]
Here is the crash report
[crash-2021-09-19_10.42.34-client.txt](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/7190911/crash-2021-09-19_10.42.34-client.txt)

**Comment by Drillgon200** [comment]
You're probably using the curse version then. New release soon should fix that.
