### ISSUE TITLE
Screen Flashing Issue

### ISSUE THREAD

**Issue by Combineadvisor** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#134]
When Loading Up a Game with the latest version of the mod, My Screen starts to rapidly Flash Before completely freezing. Please Help!

**Comment by Drillgon200** [comment]
Disable shaders in the config, option is "enableShaders2".

**Comment by Drillgon200** [comment]
Send your config with it off so I can make sure you actually did it correctly. Also send a log.
