### ISSUE TITLE
Can I disable the nuke part?

### ISSUE THREAD

**Issue by Desoroxxx** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#136]
This mod is really cool and well I am preparing a server but the nukes are not my cup of tea, so is there a way to disable the bomb part?

And by the way is it allowed in mod pack/server?

**Comment by Drillgon200** [comment]
Check the config, I believe there are bomb configs. This mod is licensed under GPLv3, use it wherever you want.

**Comment by divine-ray** [comment]
You can practically disable the functionality of the nukes by setting their radius in the config to something comically small like 10 blocks or something
