### ISSUE TITLE
[1.12.2] Game crashes if a Metastable Ingot goes boom near some Tetra Forged Blocks.

### ISSUE THREAD

**Issue by SonicX8000** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#138]
Minecraft: 1.12.2
Forge: 14.23.5.2855

Mods: 4
BiomesOPlenty-1.12.2-7.0.1.2444-universal
hbm-1.4.4a
jei_1.12.2-4.16.1.302
tetra-1.12.2-0.39.1

Report:
https://hastebin.com/epixagacor.rb

=====

Was messing around in a single-player world with these Metastable Ingots which go boom if held for too long and apparently it crashes if some blocks from Tetra get caught in the blast.

Tetra Forged Blocks can be found in cold-like biomes underground... although you can spawn them prob from jei or creative if need be.

P.S.
These Metastable Ingots are kept if 'keepInventory' is set to true, meaning that you may lose your base if you don't get rid of the ingots in time. Perhaps they could be removed once they explode?

**Comment by Drillgon200** [comment]
It's not just metastable ingots, it's a lot of things. That block requires an explosion entity to determine the explosion resistance, but unfortunately there is no such entity present in most of NTM's call to that method. I've switched them all to a deprecated method that doesn't take an explosion entity as a parameter, so hopefully that'll fix it.
