### ISSUE TITLE
[1.12.2] Mini Nukes & MIRV Ammo appears to be unobtainable?

### ISSUE THREAD

**Issue by SonicX8000** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#139]
For nukes... there is a 'hbm:gun_fatman_ammo' that you can craft but it appears that it isn't the right ammo type to load for the Catapults. There looks to be other types of ammo called...

hbm:ammo_nuke
hbm:ammo_nuke_low
hbm:ammo_nuke_high
hbm:ammo_nuke_tots
hbm:ammo_nuke_safe
hbm:ammo_nuke_pumpkin

...those get loaded into the Catapults just fine but there seems to be no way of getting these as they don't have any recipes.

=====

The Experimental MIRV can be crafted but no ammo can be used with it. The 'hbm:gun_mirv_ammo' are craft-able but can't be used with it. Upon a closer look... it's the same problem as with the nukes.

These ammo types are...

hbm:ammo_mirv
hbm:ammo_mirv_low
hbm:ammo_mirv_high
hbm:ammo_mirv_safe

...those get loaded into the Catapults just fine but there seems to be no way of getting these as they don't have any recipes.

**Comment by Joey-Destroyah** [comment]
Must be a deprecated ammo source ¯\_(ツ)_/¯

**Comment by Drillgon200** [comment]
I don't think so, it's more likely that I forgot to add the crafting recipes when I ported the new mini nuke system.
