### ISSUE TITLE
Issue with rbmk

### ISSUE THREAD

**Issue by Boon91** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#144]
Rbmk water pipes are seemingly unconnectable to rbmk steam connector plus the cooling towers aren't accepting the low pressure steam  and said steam will not come out of the turbines to be run to it I assume these are known issues I just wanted bring them to light if not

**Comment by Drillgon200** [comment]
That's intentional. Water pipes aren't supposed to connect to the steam connecter, water connects to the steam channel, the connector is only for outputting steam so it only connects to steam.

Cooling towers definitely do accept low pressure steam in testing, and output water. What exact setup do you have for it? Have you tried simply putting low pressure steam through it with a fluid tank to output water into another fluid tank?

**Comment by Boon91** [comment]
I ended up figuring out the steam connectors but it still didn't output steam it never left the the steam channels (am I missing something lol) im pretty sure you're supposed to go from ultra dense to super dense to dense to steam and the low pressure in the turbines then cooling tower then water goes back into the tank I'd tell you exactly how but we'll with it not letting steam out of the steam channels you can guess what happened

**Comment by Drillgon200** [comment]
Did you make sure to set the boiler to make ultra dense steam? I'm pretty sure it makes regular by default. If it still doesn't work, screenshot your setup.

**Comment by Boon91** [comment]
Yeah I set all of them still never left right up until it exploded the cooling towers didn't work even with a whole tank of low pressure steam tried three different containers thinking it could be the new ones but bumpkiss the ultra dense didn't even make it out im finding more and more of a reason to not try again as this is on my server and if it's just gonna keep exploding with logical builds then I don't wanna risk it again I got alot to clean up now as is lol

**Comment by Boon91** [comment]
![Uploading 2021-10-01_02.15.43.png…](
![Uploading 2021-10-01_02.15.51.png…]()
)

**Comment by Drillgon200** [comment]
That image did not upload correctly. Were the tanks set to output?

**Comment by Boon91** [comment]
i figured it out its an incompatibility with nuclear craft it has its own low pressure steam and i think something just got messed up (83 mods on a server and it never occured to me....) sorry about all this man but atleast i can mess with it now lol
