### ISSUE TITLE
Machines not having proper input/output for cables

### ISSUE THREAD

**Issue by whatsapp2** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#148]
I've been messing around in survival with the latest hbm version, it seems that the Assembly Machine and Chemical Reactor have no proper ways to input/output via cables/conduits/pipes from other mods, they can only be connected from the bottom, even then, items can't be input/output from there.

It's more of a suggestion/enhancement to automate the machinery without using too much space in one location 

![2021-10-02_00 54 39](https://user-images.githubusercontent.com/25994176/135705491-2f0b8d0d-8e06-4f56-9382-42ebe108e488.png)

**Comment by Drillgon200** [comment]
There a chutes that can output to chests. Attach the pipes to those chests instead.
