### ISSUE TITLE
Oil drilling can't work

### ISSUE THREAD

**Issue by NikaidoKio** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#15]
Oil drilling is not working properly，The drill bit goes through the oil rock，Won't suck crude oil。
forge1.12.2-14.23.5.2854
hbm-1.3.5a-1.12.2
jre1.8.0_191

**Comment by Drillgon200** [comment]
Pretty sure this was a bug in the 1.7 version, too. Bob fixed it, I just haven't ported it yet.

**Comment by NikaidoKio** [comment]
> 可以肯定的是，这也是1.7版本中的错误。鲍勃修复了它，我还没有移植。

This bug has been fixed in 1.7.10。I'm looking forward to the next update to fix this。
Thank you. I'll always support you
