### ISSUE TITLE
Crash when using a Geiger counter

### ISSUE THREAD

**Issue by luckybl0ck** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#157]
**Crash report:** https://paste.helpch.at/adosinecoh.cs
**Server version:** `Mohist version 1.12.2-261 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2855)`
**HBM's NT version:** `1.6.0a`

**Comment by Drillgon200** [comment]
Update mod.

**Comment by TheOriginalGolem** [comment]
Also dont use Mohist, they implemented an extremely broken and buggy version of bukkit, and have done some shady things.
https://essentialsx.net/do-not-use-mohist.html

If you need spigot plugins with forge, I would recommend Magma, as their implementation of the api is compliant with spigot standards, plus its based on paper, so you would get all it's performance improvements and enhancements.

**Comment by luckybl0ck** [comment]
The problem was resolved after updating mod.
