### ISSUE TITLE
water fluid duct wont connect to rbmk steam connector

### ISSUE THREAD

**Issue by Canina-X** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#159]
So i am trying to build a rbmk reactor, and i am done with the reactor thingy, now I'm building the pipes... I cannot attach the water fluid duct to rbmk steam connector... I am using the newest version. It would be nice if you can help me!

**Comment by Drillgon200** [comment]
There is no bug here. Water ducts do not connect to the steam connector. The connector does not accept water input, it only does steam output. The water ducts connect to the column while the steam ducts get steam from the connector.

**Comment by Canina-X** [comment]
... Steam connecters need water ducts, for getting an rbmk reactor working.. So i tried the original version 1.710 and it worked. If you can please fix that.

**Comment by Drillgon200** [comment]
No. This is not a bug. The steam connectors have nothing to do with water. They only exist for the column to output steam. The water ducts connect to the column itself to input water.

**Comment by Drillgon200** [comment]
Besides that, the steam ducts don't even really connect to the steam connector. It's a purely visual connection.
