### ISSUE TITLE
A couple issues

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#16]
In all furnaces, if you smelt a non-smeltable item, it will dissapear with no result
All fluids look like water
The mercury bottles are still not completely fixed (you can only put them into a tank)

**Comment by Drillgon200** [comment]
1. Fixed
2. Where do all fluids look like water?
3. When do you ever need to fill a bottle of mercury from a tank?

**Comment by TheForge129** [comment]
2. Poisonous Mud and Green Ooze
3. That's not what i meant, i meant you can't fill, say, a chemical plant
with a mercury bottle

**Comment by Drillgon200** [comment]
2. Fixed (I think).
3. Oh, that's annoying to fix. I don't know how many machines might have that problem.

**Comment by Drillgon200** [comment]
Eh, that's about as far as I feel like checking it for now. Reopen if you find any other bugs like that.
