### ISSUE TITLE
hey look he has even more problems

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#17]
Carl Gustav rifle can't shoot shrapnel rockets
ZPE Generator doesn't seem to work
oh also chemical rockets do nothing when they hit

**Comment by Drillgon200** [comment]
It can shoot them for me.
ZPE generator is also working for me, how are you setting it up?
Chemical 84mm rockets are also working for me (they're supposed to spawn some particles that give you bad potion effects).

**Comment by Drillgon200** [comment]
Alright I'm just going to close this for now, unless you show a video or find a mod that's causing it to not work or something.

**Comment by TheForge129** [comment]
yeah the chem rocket was me being bad, shouldve closed a while back but was
lazy
