### ISSUE TITLE
I am having problems with fast rendering and the config file, I have disabled them both but it still crashes...

### ISSUE THREAD

**Issue by Sapient805** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#172]
I have another mod installed called foam fix and I am also running OPtifine 1.12.2_HD_U_G5 and disabled fast render.. ran the game without foam fix installed and it was fine without the mod (foam fix and HBM) and I also set "enableShaders2" in HBM's config to false and it still crashes when i try to run the game with the config set right.. anyways i have a crash log down below could you point me into the write direction...it also displays this text when it crashes.  
___________________________________________________________________________________________
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
Exit Code: -1
___________________________________________________________________________________________
and here is the crash report.

[crash-2021-11-08_11.38.04-clientupload..txt](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/7500091/crash-2021-11-08_11.38.04-clientupload.txt)

anyways much help is needed.. and thank you!

**Comment by TheOriginalGolem** [comment]
Well with all the other mods you have installed as well, no wonder you ran out of IDs, to fix it use this mod:
https://www.curseforge.com/minecraft/mc-mods/jeid

Then it should work fine.

**Comment by Drillgon200** [comment]
Not an NTM issue.
