### ISSUE TITLE
RBMK design issue

### ISSUE THREAD

**Issue by HaxerCoder** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#175]
Hello, I am having issues with getting the RBMK to work, the steam connectors _Do not_ connect to water, is it intended? I'm on mod version 1.6.4, the latest one. Thank you for if you can respond.

**Comment by HaxerCoder** [comment]
![2021-11-12_09 37 02](https://user-images.githubusercontent.com/72237944/141510480-8876c8bf-fb91-4410-801d-7fda04c992d9.png)
Screenshot

**Comment by TheOriginalGolem** [comment]
Not a bug, thats how it is, look at issue #159 as it should explain more.

**Comment by Drillgon200** [comment]
Intentional, it will work as expected.
