### ISSUE TITLE
OpenGL Error

### ISSUE THREAD

**Issue by IamNotIntelligent** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#176]
I Opened The World And That I Can See Its You White/Black Screen But I can interact Everything, Breaking Blocks Etc Etc 
And The Chat Says OpenGL Error : 1281 (Invalid Value)

Even I Turn Off The Fast Render On Optifine And 
I tried to remove the optifine but it still same

**Comment by TheOriginalGolem** [comment]
Go to hbm's config and change "enableShaders2" to false. If that doesn't work then can you send your log.

**Comment by IamNotIntelligent** [comment]
Thx Its Working
