### ISSUE TITLE
Tom

### ISSUE THREAD

**Issue by Froooz** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#177]
Tom extinction event port when?

**Comment by Joey-Destroyah** [comment]
I think he stopped updating or put it on hiatus. IDK when he will be back

**Comment by Froooz** [comment]
he still does ports of specific things, not whole updates tho

**Comment by Froooz** [comment]
like the RBMK for example

**Comment by Joey-Destroyah** [comment]
Ok. I still don't know when he will do it.

**Comment by TheOriginalGolem** [comment]
He is busy, he will port what he wants.

**Comment by Drillgon200** [comment]
This will be ported along with the other new stuff when I take a break from other programming.
