### ISSUE TITLE
i'm just unsure about this

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#18]
Got the hidden catalog achievement...
so how do i make it?

**Comment by TheForge129** [comment]
get a load of this idiot lol

**Comment by Drillgon200** [comment]
You can get it from a sign by typing in the correct passcodes you get by solving the riddle here if I remember correctly.
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/wiki/Hidden-Catalog-Puzzle

**Comment by TheForge129** [comment]
blegh, i thought the killing an enderman with a falling boxcar thing
replaced the riddle

**Comment by Drillgon200** [comment]
Nope, that's just an extra thing you have to do.
