### ISSUE TITLE
HBM Upgrade Version

### ISSUE THREAD

**Issue by idaghan** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#181]
Hey Drillgon200. I love HBM Nuclear Tech mod. But my friend likes to play in new versions. Can you please port the mod to version 1.16.5. Please i'm following you. Thanxs.

**Comment by Joey-Destroyah** [comment]
Idk. He said he is not doing features anymore, bit I don't know.

**Comment by Drillgon200** [comment]
No. If you want a later version, you'll have to wait for MartinTheDragon's port, though I think he's doing it for 1.18 now.
