### ISSUE TITLE
Completely white screen when in game.

### ISSUE THREAD

**Issue by Gamingyaaa** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#182]
Whenever I load into a game with this mod it is just white screen even the GUI is overlapped by the white screen.
It might be a conflict with another mod but it works just fine without this mod.

**Comment by TheOriginalGolem** [comment]
Do you have Optifine installed? if so turn off fast render, if that doesn't work, open HBM's config and change "enableShaders2" from true to false.

**Comment by Gamingyaaa** [comment]
Yes I had Optifine installed, that's probably it.
