### ISSUE TITLE
Rendering bugs on multiplayer

### ISSUE THREAD

**Issue by jet-rain** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#185]
I have a multiplayer server running with Optifine, there seems to be some errors where the gas mask model appears on other players while one wears it, (I used the helmet attachable) and the gas mask doesn't really follow the player while crouching. Also, sometimes the glass in some multiblock models will turn black. Also sometimes mapping the reload key to something else crashes the game when you have a gun.

**Comment by TheOriginalGolem** [comment]
I'm not sure whats happening with the gas mask, the glass of machines are turning black due to optifine, and the crash, ik of it, but can you please upload crash report, it'll help.

**Comment by jet-rain** [comment]
Here, this happens when the reload key is mapped to something other than R, then when you equip the gun

---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroMinimapPlugin (Xaeros_Minimap_21.22.5_Forge_1.12.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  weaponlib (mw_2.0-0.4.6.2_mc1.12.2.jar)
  SoundUnpack (OpenSecurity-1.12.2-1.0-83.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  Aqua Acrobatics Transformer (AquaAcrobatics-v1.3.5-1.12.2.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 12/26/21 12:00 PM
Description: Ticking entity

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at com.hbm.items.weapon.ItemGunBase.updateClient(ItemGunBase.java:137)
	at com.hbm.items.weapon.ItemGunBase.func_77663_a(ItemGunBase.java:94)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1011)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at com.hbm.items.weapon.ItemGunBase.updateClient(ItemGunBase.java:137)
	at com.hbm.items.weapon.ItemGunBase.func_77663_a(ItemGunBase.java:94)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1011)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 991
	Entity Name: scratchyxD
	Entity's Exact location: 161.50, 65.00, 248.50
	Entity's Block location: World: (161,65,248), Chunk: (at 1,4,8 in 10,15; contains blocks 160,0,240 to 175,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['scratchyxD'/991, l='MpServer', x=161.50, y=65.00, z=248.50]]
	Chunk stats: MultiplayerChunkCache: 532, 532
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (160,64,252), Chunk: (at 0,4,12 in 10,15; contains blocks 160,0,240 to 175,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 376 game time, 376 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 112 total; [EntityCrab['Crab'/21, l='MpServer', x=82.50, y=63.00, z=253.50], EntityCrab['Crab'/22, l='MpServer', x=92.79, y=64.00, z=255.25], EntityCrab['Crab'/23, l='MpServer', x=93.50, y=64.00, z=252.50], EntityItem['item.item.quark:root'/25, l='MpServer', x=98.81, y=31.00, z=209.02], EntitySheep['Sheep'/31, l='MpServer', x=147.23, y=63.00, z=271.48], EntitySheep['Sheep'/32, l='MpServer', x=144.71, y=64.00, z=267.87], EntityChicken['Chicken'/37, l='MpServer', x=156.50, y=63.00, z=293.50], EntityChicken['Chicken'/48, l='MpServer', x=187.50, y=63.00, z=328.50], EntityChicken['Chicken'/56, l='MpServer', x=235.64, y=68.00, z=199.19], EntityChicken['Chicken'/57, l='MpServer', x=237.50, y=67.00, z=199.50], EntityChicken['Chicken'/58, l='MpServer', x=240.50, y=67.00, z=197.50], EntityChicken['Chicken'/59, l='MpServer', x=241.50, y=67.00, z=199.50], EntitySkeleton['Skeleton'/2391, l='MpServer', x=123.50, y=51.00, z=243.50], EntityItem['item.item.seeds'/2392, l='MpServer', x=162.39, y=64.00, z=283.60], EntitySkeleton['Skeleton'/2407, l='MpServer', x=124.50, y=27.00, z=238.92], EntitySkeleton['Skeleton'/2408, l='MpServer', x=127.50, y=27.00, z=240.50], EntitySkeleton['Skeleton'/2417, l='MpServer', x=124.50, y=27.00, z=239.89], EntitySkeleton['Skeleton'/2418, l='MpServer', x=188.50, y=43.00, z=281.50], EntityStoneling['Stoneling'/2577, l='MpServer', x=230.50, y=17.00, z=251.50], EntityCreeper['Creeper'/2579, l='MpServer', x=164.50, y=16.00, z=257.50], EntityCreeper['Creeper'/2580, l='MpServer', x=167.50, y=16.00, z=257.50], EntitySkeleton['Skeleton'/2584, l='MpServer', x=238.50, y=46.00, z=279.29], EntitySkeleton['Skeleton'/2585, l='MpServer', x=210.50, y=27.00, z=249.50], EntitySkeleton['Skeleton'/2594, l='MpServer', x=208.29, y=28.00, z=253.51], EntityStoneling['Stoneling'/2595, l='MpServer', x=233.42, y=17.00, z=257.06], EntitySpider['Spider'/2596, l='MpServer', x=112.70, y=44.10, z=230.30], EntityCreeper['Creeper'/2601, l='MpServer', x=195.50, y=40.00, z=245.50], EntitySkeleton['Skeleton'/2605, l='MpServer', x=83.50, y=51.00, z=253.50], EntityCreeper['Creeper'/2606, l='MpServer', x=95.43, y=51.00, z=252.78], EntityCreeper['Creeper'/2607, l='MpServer', x=82.50, y=51.00, z=252.50], EntityCreeper['Creeper'/2609, l='MpServer', x=82.50, y=51.00, z=253.50], EntityZombieVillager['Zombie Villager'/2648, l='MpServer', x=127.50, y=29.00, z=251.50], EntityZombieVillager['Zombie Villager'/2649, l='MpServer', x=129.50, y=29.00, z=250.50], EntityZotzpyre['Zotzpyre'/2650, l='MpServer', x=127.50, y=29.00, z=250.50], EntityCreeper['Creeper'/2651, l='MpServer', x=133.54, y=26.00, z=257.65], BuilderEntityRenderForwarder['entity.mts_entity_renderer.name'/2655, l='MpServer', x=161.80, y=66.21, z=247.64], BuilderEntityExisting['entity.mts_entity.name'/2656, l='MpServer', x=161.50, y=65.00, z=248.50], EntitySkeleton['Skeleton'/2657, l='MpServer', x=122.50, y=17.00, z=225.50], EntitySkeleton['Skeleton'/2658, l='MpServer', x=106.50, y=39.00, z=273.50], EntityZombie['Zombie'/2659, l='MpServer', x=87.50, y=43.00, z=239.50], EntityCreeper['Creeper'/2660, l='MpServer', x=120.50, y=29.00, z=307.50], EntityCreeper['Creeper'/2661, l='MpServer', x=86.50, y=22.00, z=258.50], EntitySkeleton['Skeleton'/2671, l='MpServer', x=232.50, y=16.00, z=254.50], EntityCreeper['Creeper'/2672, l='MpServer', x=100.50, y=35.00, z=194.50], EntityZombie['Zombie'/2707, l='MpServer', x=148.80, y=34.00, z=300.49], EntityZombie['Zombie'/2708, l='MpServer', x=147.81, y=34.00, z=303.51], EntitySkeleton['Skeleton'/2709, l='MpServer', x=237.72, y=19.00, z=251.49], EntityStoneling['Stoneling'/2710, l='MpServer', x=236.50, y=20.00, z=242.50], EntityZotzpyre['Zotzpyre'/2713, l='MpServer', x=122.50, y=29.00, z=191.50], EntityStoneling['Stoneling'/2715, l='MpServer', x=231.50, y=20.00, z=245.50], EntityItem['item.item.seeds'/2735, l='MpServer', x=165.26, y=64.00, z=282.35], EntityItem['item.item.quark:root_white_flower'/2737, l='MpServer', x=183.87, y=13.00, z=287.13], EntityItem['item.item.dyePowder.black'/2741, l='MpServer', x=97.79, y=47.00, z=286.17], EntityItem['item.item.quark:root'/2743, l='MpServer', x=104.18, y=41.00, z=240.25], EntityItem['item.item.dyePowder.black'/2750, l='MpServer', x=102.99, y=52.00, z=287.02], EntityItem['item.item.quark:root_white_flower'/2756, l='MpServer', x=104.26, y=39.00, z=244.15], EntityItem['item.item.quark:root'/2759, l='MpServer', x=104.26, y=39.00, z=244.19], EntityItem['item.item.seeds'/2767, l='MpServer', x=184.73, y=63.00, z=187.68], EntityCreeper['Creeper'/1303, l='MpServer', x=146.50, y=28.00, z=211.50], EntitySkeleton['Skeleton'/1305, l='MpServer', x=89.50, y=39.00, z=283.50], EntityZotzpyre['Zotzpyre'/1306, l='MpServer', x=201.50, y=28.00, z=260.50], EntitySkeleton['Skeleton'/1307, l='MpServer', x=202.50, y=28.00, z=263.50], EntitySkeleton['Skeleton'/1308, l='MpServer', x=95.50, y=41.00, z=289.50], EntityBat['Bat'/1309, l='MpServer', x=84.69, y=28.19, z=243.25], EntityBat['Bat'/1310, l='MpServer', x=175.57, y=10.63, z=235.07], EntityShark['Shark'/1312, l='MpServer', x=100.03, y=59.15, z=287.85], EntityShark['Shark'/1313, l='MpServer', x=102.40, y=58.66, z=282.83], EntityShark['Shark'/1314, l='MpServer', x=99.17, y=59.15, z=284.58], EntityShark['Shark'/1315, l='MpServer', x=103.70, y=62.11, z=287.31], EntityCreeper['Creeper'/1413, l='MpServer', x=96.50, y=41.00, z=283.50], EntitySpider['Spider'/1415, l='MpServer', x=197.50, y=15.00, z=214.50], EntityZombie['Zombie'/1513, l='MpServer', x=219.50, y=38.00, z=285.50], EntityStoneling['Stoneling'/1529, l='MpServer', x=231.50, y=17.00, z=251.50], EntityBat['Bat'/1530, l='MpServer', x=84.79, y=39.33, z=226.29], EntityEnderman['Enderman'/1550, l='MpServer', x=98.43, y=41.00, z=286.53], EntityCreeper['Creeper'/1551, l='MpServer', x=96.50, y=41.00, z=280.50], EntityZotzpyre['Zotzpyre'/1552, l='MpServer', x=207.50, y=35.96, z=238.50], EntityCreeper['Creeper'/1553, l='MpServer', x=158.80, y=12.00, z=225.60], EntitySkeleton['Skeleton'/1554, l='MpServer', x=156.50, y=31.00, z=297.50], EntityBat['Bat'/1555, l='MpServer', x=238.74, y=40.34, z=256.99], EntityItem['item.tile.flower1.dandelion'/1562, l='MpServer', x=177.95, y=62.00, z=278.25], EntitySkeleton['Skeleton'/1563, l='MpServer', x=216.50, y=33.00, z=255.50], EntityBat['Bat'/1564, l='MpServer', x=143.92, y=57.18, z=304.81], EntityCreeper['Creeper'/1569, l='MpServer', x=110.50, y=30.00, z=232.50], EntityBat['Bat'/1570, l='MpServer', x=191.35, y=44.09, z=323.75], EntitySkeleton['Skeleton'/1571, l='MpServer', x=103.92, y=38.00, z=273.30], EntityBat['Bat'/1572, l='MpServer', x=93.08, y=43.98, z=219.36], EntityBat['Bat'/1573, l='MpServer', x=204.82, y=30.17, z=254.50], EntityCreeper['Creeper'/1574, l='MpServer', x=89.50, y=51.00, z=255.50], EntityBat['Bat'/1575, l='MpServer', x=239.34, y=40.68, z=266.69], EntityBat['Bat'/1576, l='MpServer', x=133.74, y=16.34, z=215.68], EntityBat['Bat'/1578, l='MpServer', x=163.04, y=29.00, z=210.96], EntitySkeleton['Skeleton'/1579, l='MpServer', x=93.70, y=51.00, z=254.61], EntityBat['Bat'/1580, l='MpServer', x=164.47, y=29.00, z=213.75], EntityBat['Bat'/1581, l='MpServer', x=163.71, y=29.00, z=214.49], EntityBat['Bat'/1582, l='MpServer', x=90.12, y=41.78, z=207.30], EntityCreeper['Creeper'/1583, l='MpServer', x=88.15, y=51.00, z=253.59], EntityBat['Bat'/1584, l='MpServer', x=204.10, y=23.81, z=205.75], EntityZotzpyre['Zotzpyre'/1585, l='MpServer', x=213.50, y=17.00, z=301.50], EntityZombie['Zombie'/1586, l='MpServer', x=224.50, y=35.00, z=287.50], EntityCreeper['Creeper'/1587, l='MpServer', x=224.70, y=35.00, z=286.30], EntityCreeper['Creeper'/1588, l='MpServer', x=181.50, y=18.00, z=258.50], EntitySkeleton['Skeleton'/1589, l='MpServer', x=136.50, y=59.00, z=319.50], EntityBat['Bat'/1590, l='MpServer', x=201.20, y=26.02, z=208.75], EntityZombie['Zombie'/1592, l='MpServer', x=234.50, y=33.00, z=260.50], EntityZombie['Zombie'/1594, l='MpServer', x=197.50, y=44.00, z=303.50], EntitySpider['Spider'/1596, l='MpServer', x=235.50, y=42.00, z=272.50], EntityZotzpyre['Zotzpyre'/1597, l='MpServer', x=164.87, y=17.00, z=259.04], EntitySkeleton['Skeleton'/1598, l='MpServer', x=115.50, y=48.00, z=190.50], EntityCreeper['Creeper'/1599, l='MpServer', x=167.50, y=16.00, z=255.50], EntityPlayerSP['scratchyxD'/991, l='MpServer', x=161.50, y=65.00, z=248.50], EntitySkeleton['Skeleton'/1601, l='MpServer', x=117.50, y=15.00, z=223.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 656390880 bytes (625 MB) / 3441426432 bytes (3282 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version             | Source                                          | Signature                                |
	|:------ |:--------------------- |:------------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2              | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                   | 9.42                | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                   | 8.0.99.99           | forge-1.12.2-14.23.5.2855.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2855        | forge-1.12.2-14.23.5.2855.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core     | 1.12.2-1.0          | minecraft.jar                                   | None                                     |
	| LCHIJA | opencomputers|core    | 1.7.5.192           | minecraft.jar                                   | None                                     |
	| LCHIJA | aquaacrobatics        | 1.3.5               | AquaAcrobatics-v1.3.5-1.12.2.jar                | None                                     |
	| LCHIJA | jei                   | 4.16.1.301          | jei_1.12.2-4.16.1.301.jar                       | None                                     |
	| LCHIJA | quark                 | r1.6-179            | Quark-r1.6-179.jar                              | None                                     |
	| LCHIJA | autoreglib            | 1.3-32              | AutoRegLib-1.3-32.jar                           | None                                     |
	| LCHIJA | biomesoplenty         | 7.0.1.2444          | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar   | None                                     |
	| LCHIJA | ctm                   | MC1.12.2-1.0.2.31   | CTM-MC1.12.2-1.0.2.31.jar                       | None                                     |
	| LCHIJA | chisel                | MC1.12.2-1.0.2.45   | Chisel-MC1.12.2-1.0.2.45.jar                    | None                                     |
	| LCHIJA | chiselsandbits        | 14.33               | chiselsandbits-14.33.jar                        | None                                     |
	| LCHIJA | codechickenlib        | 3.2.3.358           | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux          | 2.1.1               | RedstoneFlux-1.12-2.1.1.1-universal.jar         | None                                     |
	| LCHIJA | cofhcore              | 4.6.6               | CoFHCore-1.12.2-4.6.6.1-universal.jar           | None                                     |
	| LCHIJA | cofhworld             | 1.4.0               | CoFHWorld-1.12.2-1.4.0.1-universal.jar          | None                                     |
	| LCHIJA | collective            | 3.0                 | collective-1.12.2-3.0.jar                       | None                                     |
	| LCHIJA | asielib               | 1.0.0               | Computronics-1.12.2-1.6.6.jar                   | None                                     |
	| LCHIJA | opencomputers         | 1.7.5.192           | OpenComputers-MC1.12.2-1.7.5.192.jar            | None                                     |
	| LCHIJA | computronics          | 1.6.6               | Computronics-1.12.2-1.6.6.jar                   | None                                     |
	| LCHIJA | extendedrenderer      | v1.0                | coroutil-1.12.1-1.2.37.jar                      | None                                     |
	| LCHIJA | coroutil              | 1.12.1-1.2.37       | coroutil-1.12.1-1.2.37.jar                      | None                                     |
	| LCHIJA | configmod             | v1.0                | coroutil-1.12.1-1.2.37.jar                      | None                                     |
	| LCHIJA | corpse                | 1.12.2-1.0.8        | corpse-1.12.2-1.0.8.jar                         | None                                     |
	| LCHIJA | craftstudioapi        | 1.0.0               | CraftStudio-1.0.0.93-mc1.12-alpha.jar           | None                                     |
	| LCHIJA | forgemultipartcbe     | 2.6.2.83            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe         | 2.6.2.83            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
	| LCHIJA | minecraftmultipartcbe | 2.6.2.83            | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
	| LCHIJA | cfm                   | 6.3.1               | furniture-6.3.1-1.12.2.jar                      | None                                     |
	| LCHIJA | hbm                   | hbm-1.6.4.1A-1.12.2 | hbm-1.6.4a-Gv1.jar                              | None                                     |
	| LCHIJA | mts                   | 20.4.0              | Immersive Vehicles-1.12.2-20.4.0.jar            | None                                     |
	| LCHIJA | trackapi              | 1.2                 | TrackAPI-1.2.jar                                | None                                     |
	| LCHIJA | universalmodcore      | 1.1.3               | UniversalModCore-1.12.2-forge-1.1.3.jar         | None                                     |
	| LCHIJA | immersiverailroading  | 1.9.1               | ImmersiveRailroading-1.12.2-forge-1.9.1.jar     | None                                     |
	| LCHIJA | mca                   | 6.1.0               | MCA-1.12.2-6.1.0-universal.jar                  | None                                     |
	| LCHIJA | movingelevators       | 1.2.34              | movingelevators-1.2.34-mc1.12.jar               | None                                     |
	| LCHIJA | mw                    | 0.4.6.2             | mw_2.0-0.4.6.2_mc1.12.2.jar                     | None                                     |
	| LCHIJA | opensecurity          | 1.0-83              | OpenSecurity-1.12.2-1.0-83.jar                  | None                                     |
	| LCHIJA | patchouli             | 1.0-23.6            | Patchouli-1.0-23.6.jar                          | None                                     |
	| LCHIJA | thermalfoundation     | 2.6.7               | ThermalFoundation-1.12.2-2.6.7.1-universal.jar  | None                                     |
	| LCHIJA | thermaldynamics       | 2.5.6               | ThermalDynamics-1.12.2-2.5.6.1-universal.jar    | None                                     |
	| LCHIJA | travelersbackpack     | 1.0.35              | TravelersBackpack-1.12.2-1.0.35.jar             | None                                     |
	| LCHIJA | treeharvester         | 4.0                 | treeharvester_1.12.2-4.0.jar                    | None                                     |
	| LCHIJA | twilightforest        | 3.11.1021           | twilightforest-1.12.2-3.11.1021-universal.jar   | None                                     |
	| LCHIJA | unuparts              | 5.0.0               | UNU Parts Pack [MTS] 1.12.2-20.4.0-5.0.0.jar    | None                                     |
	| LCHIJA | unucivil              | 5.0.1               | UNU Civilian Pack [MTS] 1.12.2-20.4.0-5.0.1.jar | None                                     |
	| LCHIJA | weather2              | 1.12.1-2.6.12       | weather2-1.12.1-2.6.12.jar                      | None                                     |
	| LCHIJA | worldedit             | 6.1.10              | worldedit-forge-mc1.12.2-6.1.10-dist.jar        | None                                     |
	| LCHIJA | wrcbe                 | 2.3.2               | WR-CBE-1.12.2-2.3.2.33-universal.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | xaerominimap          | 21.22.5             | Xaeros_Minimap_21.22.5_Forge_1.12.jar           | None                                     |
	| LCHIJA | betteranimalsplus     | 9.0.1               | betteranimalsplus-1.12.2-9.0.1.jar              | None                                     |

	Loaded coremods (and transformers): 
XaeroMinimapPlugin (Xaeros_Minimap_21.22.5_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
weaponlib (mw_2.0-0.4.6.2_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
SoundUnpack (OpenSecurity-1.12.2-1.0-83.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Aqua Acrobatics Transformer (AquaAcrobatics-v1.3.5-1.12.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 462.80' Renderer: 'GeForce RTX 2070/PCIe/SSE2'
	Patchouli open book context: n/a
	Launched Version: forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 462.80, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: GamerPack
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 462.80
	OpenGlRenderer: GeForce RTX 2070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
