### ISSUE TITLE
Particle accelerator works only with copper tier coils [1.6.4a]

### ISSUE THREAD

**Issue by QuadBitBrain** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#189]
If you try to use any of higher tiers coils - explosion occures in place where first coil of higher tier starts. 
Every coil has its own plug with infinite spark storage - so its not issue of wrong powering. 
If accelerator constructed only from copper coils it works as intended.

**Comment by TheOriginalGolem** [comment]
Same as issue #149

**Comment by QuadBitBrain** [comment]
Duplicate of #149
