### ISSUE TITLE
Water fluid is not connecting to steam glitch

### ISSUE THREAD

**Issue by NONPLAYT** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#193]
![image](https://user-images.githubusercontent.com/76615486/148807327-0f992ce9-db10-4593-b7a8-b42a4bdc11e9.png)
ultra dense steam is connected, but water no. in think this is a vision glitch, can is this be fixed?

**Comment by TheForge129** [comment]
Duplicate of previous issues
