### ISSUE TITLE
Steam Connector Wont connect To Water Pipe

### ISSUE THREAD

**Issue by AlphaWolf239** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#195]
When ever I tired to connect the water pipe to the steam connector it will not work and i know the original version you can do it there but the problem is is that it would be harder to transport water and steam without the water pipe connected to the steam connector.

**Comment by Drillgon200** [comment]
It's just visual. I didn't add the water pipe connection to the steam connector because the steam connector has nothing to do with water. It only outputs steam.
