### ISSUE TITLE
problem with using lava buckets as fuel

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#2]
When you use a bucket of lava in a blast furnace, burner press, etc you don't get your bucket back

**Comment by Drillgon200** [comment]
Alright, should be fixed for those two. Any other machines with that issue?

**Comment by TheForge129** [comment]
pretty much anything that can use furnace fuels has the issue as far as i
know

**Comment by Drillgon200** [comment]
Well the combustion generator and boiler seem to work. Are there any other machines that even use lava buckets as a fuel source?

**Comment by TheForge129** [comment]
i dont know... i got this info from a survival world, so i havent gotten that far in yet... :/

**Comment by TheForge129** [comment]
> Well the combustion generator and boiler seem to work. Are there any other machines that even use lava buckets as a fuel source?

actually, yes, the burner press
