### ISSUE TITLE
Can't disable gun module in config

### ISSUE THREAD

**Issue by Unjustifiable** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#20]
I'm trying to disable the weapons and turrets module in the Nuclear Tech Config, but it's not letting me doing it. I ticked "enable guns" to false and it's still not working.

**Comment by Drillgon200** [comment]
All the config does is make it so guns can't shoot, can they still do that?

**Comment by Unjustifiable** [comment]
Let me check, but I was kind of hoping they wouldn't be craftable either.

**Comment by Drillgon200** [comment]
If you want them to not be craftable, remove the crafting recipes with crafttweaker or something.
