### ISSUE TITLE
GC overhead limit exceeded do to HBM's Nuclear Tech Mod (hbm)

### ISSUE THREAD

**Issue by copper13** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#206]
Hay so HBM NT is Giving me a little bit of a headache with a limit exceeded crash report. I am looking into it on my side, and I was also hoping that someone might have encountered this before and have a solution or workaround. All attached the crash report along with this post.

[crash-2022-03-19_17.21.39-client.txt](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/8310410/crash-2022-03-19_17.21.39-client.txt)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  MicdoodlePlugin (Galacticraft-1.12.2-4.0.2.284.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 3/19/22 5:21 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from HBM's Nuclear Tech Mod (hbm)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:201)
	at java.lang.String.substring(String.java:1957)
	at java.lang.String.split(String.java:2341)
	at java.lang.String.split(String.java:2410)
	at com.hbm.animloader.ColladaLoader.parseFloatArray(ColladaLoader.java:274)
	at com.hbm.animloader.ColladaLoader.parseTexCoords(ColladaLoader.java:262)
	at com.hbm.animloader.ColladaLoader.parseGeometry(ColladaLoader.java:215)
	at com.hbm.animloader.ColladaLoader.parse(ColladaLoader.java:94)
	at com.hbm.animloader.ColladaLoader.load(ColladaLoader.java:55)
	at com.hbm.main.ResourceManager.loadAnimatedModels(ResourceManager.java:1440)
	at com.hbm.main.ClientProxy.postInit(ClientProxy.java:2377)
	at com.hbm.main.MainRegistry.postInit(MainRegistry.java:1022)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 479866032 bytes (457 MB) / 3817865216 bytes (3641 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 104 mods loaded, 104 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                             | Version                     | Source                                          | Signature                                |
	|:----- |:------------------------------ |:--------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft                      | 1.12.2                      | minecraft.jar                                   | None                                     |
	| LCHIJ | mcp                            | 9.42                        | minecraft.jar                                   | None                                     |
	| LCHIJ | FML                            | 8.0.99.99                   | forge-1.12.2-14.23.5.2860.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge                          | 14.23.5.2860                | forge-1.12.2-14.23.5.2860.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | micdoodlecore                  | 4.0.2.284                   | minecraft.jar                                   | None                                     |
	| LCHIJ | opencomputers|core             | 1.7.5.192                   | minecraft.jar                                   | None                                     |
	| LCHIJ | ctm                            | MC1.12.2-1.0.2.31           | CTM-MC1.12.2-1.0.2.31.jar                       | None                                     |
	| LCHIJ | appliedenergistics2            | rv6-stable-7                | appliedenergistics2-rv6-stable-7.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJ | baubles                        | 1.5.2                       | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCHIJ | bibliocraft                    | 2.4.6                       | BiblioCraft[v2.4.6][MC1.12.2].jar               | None                                     |
	| LCHIJ | biomesoplenty                  | 7.0.1.2445                  | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar   | None                                     |
	| LCHIJ | cctweaked                      | 1.89.2                      | cc-tweaked-1.12.2-1.89.2.jar                    | None                                     |
	| LCHIJ | computercraft                  | 1.89.2                      | cc-tweaked-1.12.2-1.89.2.jar                    | None                                     |
	| LCHIJ | chameleon                      | 1.12-4.1.3                  | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| LCHIJ | jei                            | 4.16.1.301                  | jei_1.12.2-4.16.1.301.jar                       | None                                     |
	| LCHIJ | chisel                         | MC1.12.2-1.0.2.45           | Chisel-MC1.12.2-1.0.2.45.jar                    | None                                     |
	| LCHIJ | chiselsandbits                 | 14.33                       | chiselsandbits-14.33.jar                        | None                                     |
	| LCHIJ | clumps                         | 3.1.2                       | Clumps-3.1.2.jar                                | None                                     |
	| LCHIJ | codechickenlib                 | 3.2.3.358                   | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ | redstoneflux                   | 2.1.1                       | RedstoneFlux-1.12-2.1.1.1-universal.jar         | None                                     |
	| LCHIJ | cofhcore                       | 4.6.6                       | CoFHCore-1.12.2-4.6.6.1-universal.jar           | None                                     |
	| LCHIJ | cofhworld                      | 1.4.0                       | CoFHWorld-1.12.2-1.4.0.1-universal.jar          | None                                     |
	| LCHIJ | controlling                    | 3.0.10                      | Controlling-3.0.10.jar                          | None                                     |
	| LCHIJ | extracpus                      | 1.12.2-1.2.1                | extracpus-1.12.2-1.2.1.jar                      | None                                     |
	| LCHIJ | extrautils2                    | 1.0                         | extrautils2-1.12-1.9.9.jar                      | None                                     |
	| LCHIJ | opencomputers                  | 1.7.5.192                   | OpenComputers-MC1.12.2-1.7.5.192.jar            | None                                     |
	| LCHIJ | zerocore                       | 1.12.2-0.1.2.9              | zerocore-1.12.2-0.1.2.9.jar                     | None                                     |
	| LCHIJ | bigreactors                    | 1.12.2-0.4.5.68             | ExtremeReactors-1.12.2-0.4.5.68.jar             | None                                     |
	| LCHIJ | flansmod                       | 5.10.0                      | Flan's Mod-1.12.2-5.10.0.jar                    | None                                     |
	| LCHIJ | forgelin                       | 1.8.4                       | Forgelin-1.8.4.jar                              | None                                     |
	| LCHIJ | forgemultipartcbe              | 2.6.2.83                    | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ | microblockcbe                  | 2.6.2.83                    | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
	| LCHIJ | minecraftmultipartcbe          | 2.6.2.83                    | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
	| LCHIJ | ftbbackups                     | 1.1.0.1                     | FTBBackups-1.1.0.1.jar                          | None                                     |
	| LCHIJ | ftblib                         | 5.4.7.2                     | FTBLib-5.4.7.2.jar                              | None                                     |
	| LCHIJ | ftbutilities                   | 5.4.1.131                   | FTBUtilities-5.4.1.131.jar                      | None                                     |
	| LCHIJ | galacticraftcore               | 4.0.2.284                   | Galacticraft-1.12.2-4.0.2.284.jar               | None                                     |
	| LCHIJ | galacticraftplanets            | 4.0.2.284                   | Galacticraft-1.12.2-4.0.2.284.jar               | None                                     |
	| LCHIE | hbm                            | hbm-1.6.4.2A-1.12.2         | hbm-1.6.4a-Gv2.jar                              | None                                     |
	| LCHI  | waila                          | 1.8.26                      | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LCHI  | icbmclassic                    | 1.12.2-4.1.0.20211106011047 | ICBM-classic-1.12.2-4.1.0b20211106011048.jar    | None                                     |
	| LCHI  | ichunutil                      | 7.2.2                       | iChunUtil-1.12.2-7.2.2.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHI  | railcraft                      | 12.0.0                      | railcraft-12.0.0.jar                            | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHI  | thermalfoundation              | 2.6.7                       | ThermalFoundation-1.12.2-2.6.7.1-universal.jar  | None                                     |
	| LCHI  | immersiveengineering           | 0.12-98                     | ImmersiveEngineering-0.12-98.jar                | None                                     |
	| LCHI  | immersivepetroleum             | 1.1.10                      | immersivepetroleum-1.12.2-1.1.10.jar            | None                                     |
	| LCHI  | immersiveposts                 | 0.2.1                       | ImmersivePosts-0.2.1.jar                        | 0ba8738eadcf158e7fe1452255a73a022fb15feb |
	| LCHI  | mekanism                       | 1.12.2-9.8.3.390            | Mekanism-1.12.2-9.8.3.390.jar                   | None                                     |
	| LCHI  | teslacorelib                   | 1.0.18                      | tesla-core-lib-1.12.2-1.0.18.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | industrialforegoing            | 1.12.2-1.12.2               | industrialforegoing-1.12.2-1.12.13-237.jar      | None                                     |
	| LCHI  | ironbackpacks                  | 1.12.2-3.0.8-12             | IronBackpacks-1.12.2-3.0.8-12.jar               | None                                     |
	| LCHI  | ironchest                      | 1.12.2-7.0.67.844           | ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
	| LCHI  | jepb                           | 1.2.1                       | jepb-1.12-1.2.1.jar                             | None                                     |
	| LCHI  | journeymap                     | 1.12.2-5.7.1                | journeymap-1.12.2-5.7.1.jar                     | None                                     |
	| LCHI  | justenoughreactors             | 1.1.3.61                    | JustEnoughReactors-1.12.2-1.1.3.61.jar          | 2238d4a92d81ab407741a2fdb741cebddfeacba6 |
	| LCHI  | jeresources                    | 0.9.2.60                    | JustEnoughResources-1.12.2-0.9.2.60.jar         | None                                     |
	| LCHI  | keywizard                      | 1.12.2-1.7.3                | keywizard-1.12.2-1.7.3.jar                      | None                                     |
	| LCHI  | kleeslabs                      | 5.4.12                      | KleeSlabs_1.12.2-5.4.12.jar                     | None                                     |
	| LCHI  | mcjtylib_ng                    | 3.5.4                       | mcjtylib-1.12-3.5.4.jar                         | None                                     |
	| LCHI  | immersivetech                  | 1.9.100                     | MCTImmersiveTechnology-1.12.2-1.9.100.jar       | None                                     |
	| LCHI  | mekanismgenerators             | 1.12.2-9.8.3.390            | MekanismGenerators-1.12.2-9.8.3.390.jar         | None                                     |
	| LCHI  | mekanismtools                  | 1.12.2-9.8.3.390            | MekanismTools-1.12.2-9.8.3.390.jar              | None                                     |
	| LCHI  | modernweaponspack              | 5.8.2                       | Modern Warfare-Content Pack-1.12.2-5.8.2.jar    | None                                     |
	| LCHI  | modroadworksreborn             | 0.0.3                       | modroadworksreborn-0.0.3.jar                    | None                                     |
	| LCHI  | scp_alarm                      | 1.0.0                       | More-SCP-Alarm-1.9.0.jar                        | None                                     |
	| LCHI  | mousetweaks                    | 2.10                        | MouseTweaks-2.10-mc1.12.2.jar                   | None                                     |
	| LCHI  | uteamcore                      | 2.2.5.147                   | u_team_core-1.12.2-2.2.5.147.jar                | None                                     |
	| LCHI  | musicplayer                    | 2.1.1.137                   | music_player-1.12.2-2.1.1.137.jar               | None                                     |
	| LCHI  | naturescompass                 | 1.8.5                       | NaturesCompass-1.12.2-1.8.5.jar                 | None                                     |
	| LCHI  | nuclearcraft                   | 2.18zz                      | NuclearCraft-2.18zz-1.12.2.jar                  | None                                     |
	| LCHI  | oldmdg                         | 1.0.0                       | oldmdg (1.1).jar                                | None                                     |
	| LCHI  | eternalsoap.icbm.opencomputers | 1.0                         | OpenComputersICBMAddon-1.3.jar                  | None                                     |
	| LCHI  | orva_alarms                    | 1.7                         | Orva Alarms 2.2 1.12.2.jar                      | None                                     |
	| LCHI  | reborncore                     | 3.19.5                      | RebornCore-1.12.2-3.19.5-universal.jar          | None                                     |
	| LCHI  | quantumstorage                 | 4.7.0                       | QuantumStorage-1.12-4.7.0.jar                   | None                                     |
	| LCHI  | quickleafdecay                 | 1.2.4                       | QuickLeafDecay-MC1.12.1-1.2.4.jar               | None                                     |
	| LCHI  | refinedstorage                 | 1.6.16                      | refinedstorage-1.6.16.jar                       | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHI  | rebornstorage                  | 1.0.0                       | RebornStorage-1.12.2-3.3.4.1.jar                | None                                     |
	| LCHI  | refinedstorageaddons           | 0.4.5                       | refinedstorageaddons-0.4.5.jar                  | None                                     |
	| LCHI  | rftools                        | 7.73                        | rftools-1.12-7.73.jar                           | None                                     |
	| LCHI  | rftoolscontrol                 | 2.0.2                       | rftoolsctrl-1.12-2.0.2.jar                      | None                                     |
	| LCHI  | rftoolsdim                     | 5.71                        | rftoolsdim-1.12-5.71.jar                        | None                                     |
	| LCHI  | rftoolspower                   | 1.2.0                       | rftoolspower-1.12-1.2.0.jar                     | None                                     |
	| LCHI  | scple                          | 3.0.0                       | SCP Labels Mod v3.0.jar                         | None                                     |
	| LCHI  | scootys_scp_mod                | 1.5                         | SCP Lockdown Heavy Expansion 1.5.jar            | None                                     |
	| LCHI  | scp                            | 2.4.0                       | SCP_Lockdown-1.12.2-2.4.0-hotfix.jar            | None                                     |
	| LCHI  | simplepartspack                | 5.7.2                       | Simple Parts-Content Pack-1.12.2-5.7.2.jar      | None                                     |
	| LCHI  | soundfilters                   | 0.12.1_for_1.12             | SoundFilters-0.12.1_for_1.12.jar                | None                                     |
	| LCHI  | lemonlib                       | 1.3.0                       | lemonlib-1.12.2-1.3.0.jar                       | None                                     |
	| LCHI  | statues                        | 1.0.1                       | statues-rechiseled-1.12.2-1.0.1.jar             | None                                     |
	| LCHI  | storagedrawers                 | 5.2.2                       | StorageDrawers-1.12.2-5.4.2.jar                 | None                                     |
	| LCHI  | sync                           | 7.1.0                       | Sync-1.12.2-7.1.0.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHI  | thermalcultivation             | 0.3.6                       | ThermalCultivation-1.12.2-0.3.6.1-universal.jar | None                                     |
	| LCHI  | thermalinnovation              | 0.3.6                       | ThermalInnovation-1.12.2-0.3.6.1-universal.jar  | None                                     |
	| LCHI  | variedcommodities              | 1.12.2                      | VariedCommodities_1.12.2-(13Jan22).jar          | None                                     |
	| LCHI  | veinminer                      | 0.38.2                      | VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
	| LCHI  | veinminermodsupport            | 0.38.2                      | VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
	| LCHI  | wailaharvestability            | 1.1.12                      | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| LCHI  | wawla                          | 2.6.275                     | Wawla-1.12.2-2.6.275.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | waystones                      | 4.1.0                       | Waystones_1.12.2-4.1.0.jar                      | None                                     |
	| LCHI  | worldedit                      | 6.1.10                      | worldedit-forge-mc1.12.2-6.1.10-dist.jar        | None                                     |
	| LCHI  | wrcbe                          | 2.3.2                       | WR-CBE-1.12.2-2.3.2.33-universal.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | immersiveintelligence          | 0.2.1                       | immersiveintelligence-0.2.1.jar                 | 770570c49a2652e64a9b29b9b9d9919ca68b7065 |
	| LCHI  | teslacorelib_registries        | 1.0.18                      | tesla-core-lib-1.12.2-1.0.18.jar                | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
MicdoodlePlugin (Galacticraft-1.12.2-4.0.2.284.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
  pl.pabilo8.immersiveintelligence.common.asm.IIClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 457.51' Renderer: 'GeForce RTX 3070/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.19.5
		Runtime Debofucsation 1
		Invalid fingerprint detected for RebornCore!
		RenderEngine: 0
	AE2 Integration: IC2:OFF, RC:ON, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:ON, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF

**Comment by copper13** [comment]
Hey so I just looked into it, and I don't even have a config file for the mod. if anyone has that could they please link it to me

**Comment by TheOriginalGolem** [comment]
Allocate more ram

**Comment by Drillgon200** [comment]
I'd try allocating more memory first. If that doesn't fix it, something weird is going on. My collada loader isn't the most optimal thing ever, but it shouldn't be using obscene amounts of memory by itself all the same.
