### ISSUE TITLE
In 1.12.2, the oil derrick and pumpjack lag back when you apply power and delete any battery or energy you apply

### ISSUE THREAD

**Issue by Globalfirestorm10** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#207]
this mainly happens when you have structures around and you go out of range for a while or leave you world.

**Comment by Drillgon200** [comment]
Could you provide a log from when this happens?

**Comment by Globalfirestorm10** [comment]
There is no log, its just a single-player world, I open the pump-jack, it fills with power, then lags back and just kicks me out of the GUI. I re-open the pumpjack to find that anything I changed (e.g, added an empty gas tank or a battery) is gone.
