### ISSUE TITLE
hunter chopper crashes your game, with the exit code  -805306369

### ISSUE THREAD

**Issue by Globalfirestorm10** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#209]
Whenever I spawn a hunter chopper, Minecraft stops responding and crashes my game with the exit code  -805306369. Doesn't matter where I spawn it.

**Comment by Drillgon200** [comment]
I need a crash report.

**Comment by Globalfirestorm10** [comment]
Hi there, there isn’t any crash report or latest.log, it just flat out gives me an exit code
