### ISSUE TITLE
Large Water Geyser Crashes Game

### ISSUE THREAD

**Issue by Sxizy** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#248]
After creating a new world I wondered into a region of intense lag to the point of which the game freezes. Unknown of the cause I began investigating whilst progressing the mod. After long 3 weeks of trying different methods I've decided to try teleporting myself into that region to get more info and found a lot of particles or some entities trying to render in(seeing all this thru Xaero's Minimap). After a few teleports and crashes I pinpointed the exact location where the _lag was being generated and it turned out to be a **Large Water Geyser**_. Once teleported in front of it, the game froze almost immediately.

At this point I'm a bit frustrated not being able to explore and expand my world, even tried MCEdit to remove the chunk but that chunk is so bad even the program crashes. I suppose this geyser was spewing out lag juice.

Some Info:
forge-14.23.5.2860
hbm-1.6.8a-Gv5
Minecraft Exit Code: -805306369

Here's a vid:
https://user-images.githubusercontent.com/112289242/187053644-74181c7e-1da3-4d46-b0d8-9c7b86df9f28.mp4

If there's any info you need or temporary fix, let me know.

**Comment by mexikoedi** [comment]
Try the newest version "hbm-1.6.9a-G".
Your issue could be fixed there.
Someone else already reported something similar. 
See here: https://github.com/TheOriginalGolem/Hbm-s-Nuclear-Tech-GIT/issues/14

**Comment by Sxizy** [comment]
Problem solved! Thanks for new version, and am enjoying this mod. Fabulous job of making this mod greater than ever before.
