### ISSUE TITLE
The game crashed whilst unexpected error Error: java.lang.IllegalAccessError: tried to access field net.minecraft.client.Minecraft.field_193996_ah from class com.hbm.main.ClientProxy Exit Code: -1

### ISSUE THREAD

**Issue by Joey-Destroyah** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#28]
Crash Report:
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 10/6/20 5:54 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.client.Minecraft.field_193996_ah from class com.hbm.main.ClientProxy
	at com.hbm.main.ClientProxy.partialTicks(ClientProxy.java:1498)
	at com.hbm.util.KeypadClient.rayTraceForButtonIndex(KeypadClient.java:104)
	at com.hbm.util.KeypadClient.rayTrace(KeypadClient.java:84)
	at com.hbm.blocks.machine.BlockSlidingBlastDoor.func_180640_a(BlockSlidingBlastDoor.java:91)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185918_c(BlockStateContainer.java:429)
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:1967)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1362)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.hbm.main.ClientProxy.partialTicks(ClientProxy.java:1498)
	at com.hbm.util.KeypadClient.rayTraceForButtonIndex(KeypadClient.java:104)
	at com.hbm.util.KeypadClient.rayTrace(KeypadClient.java:84)
	at com.hbm.blocks.machine.BlockSlidingBlastDoor.func_180640_a(BlockSlidingBlastDoor.java:91)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185918_c(BlockStateContainer.java:429)
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:1967)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1362)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Joseph_da_IT_Guy'/2240, l='MpServer', x=244.50, y=70.00, z=275.37]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (248,64,256), Chunk: (at 8,4,0 in 15,16; contains blocks 240,0,256 to 255,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4467 game time, 4467 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 104 total; [EntityDuck['Duck'/3073, l='MpServer', x=227.82, y=69.00, z=279.55], EntityZombie['Zombie'/5895, l='MpServer', x=323.50, y=11.00, z=274.50], EntityZombie['Zombie'/5385, l='MpServer', x=298.24, y=45.00, z=311.50], EntityZombie['Zombie'/5139, l='MpServer', x=262.50, y=47.00, z=305.50], EntityZombie['Zombie'/5140, l='MpServer', x=256.56, y=47.00, z=310.22], EntityZombie['Zombie'/5400, l='MpServer', x=230.50, y=25.00, z=269.50], EntitySkeleton['Skeleton'/5657, l='MpServer', x=222.50, y=37.00, z=255.50], EntityZombie['Zombie'/5149, l='MpServer', x=310.47, y=62.00, z=205.81], EntitySkeleton['Skeleton'/5150, l='MpServer', x=308.50, y=60.00, z=216.34], EntityBat['Bat'/5408, l='MpServer', x=240.84, y=46.39, z=232.65], EntityBat['Bat'/5168, l='MpServer', x=305.90, y=14.17, z=275.61], EntitySpider['Spider'/4402, l='MpServer', x=238.50, y=33.00, z=198.50], EntityBat['Bat'/5177, l='MpServer', x=249.75, y=46.10, z=311.50], EntityBat['Bat'/5178, l='MpServer', x=253.61, y=46.05, z=310.15], EntitySpider['Spider'/5954, l='MpServer', x=305.73, y=17.46, z=195.76], EntitySkeleton['Skeleton'/4935, l='MpServer', x=288.50, y=27.00, z=336.50], EntityCreeper['Creeper'/5704, l='MpServer', x=214.50, y=37.00, z=308.50], EntityCreeper['Creeper'/4937, l='MpServer', x=291.50, y=27.00, z=334.50], EntityZombie['Zombie'/5705, l='MpServer', x=189.50, y=54.00, z=266.50], EntityCreeper['Creeper'/4939, l='MpServer', x=297.50, y=47.00, z=204.50], EntitySkeleton['Skeleton'/4941, l='MpServer', x=321.50, y=28.00, z=203.28], EntitySkeleton['Skeleton'/4942, l='MpServer', x=320.50, y=27.00, z=197.50], EntityCreeper['Creeper'/5710, l='MpServer', x=270.50, y=24.00, z=337.50], EntityZombie['Zombie'/5711, l='MpServer', x=228.50, y=25.00, z=270.50], EntityEnderman['Enderman'/5714, l='MpServer', x=314.50, y=23.00, z=204.50], EntityZombie['Zombie'/3668, l='MpServer', x=302.25, y=19.00, z=205.45], EntityBat['Bat'/5462, l='MpServer', x=207.23, y=28.16, z=224.34], EntityRabbit['Rabbit'/91, l='MpServer', x=187.50, y=72.00, z=207.50], EntityRabbit['Rabbit'/92, l='MpServer', x=186.50, y=72.00, z=206.50], EntityRabbit['Rabbit'/93, l='MpServer', x=186.50, y=72.00, z=208.50], EntitySpider['Spider'/5725, l='MpServer', x=296.50, y=32.00, z=346.50], EntityChicken['Chicken'/94, l='MpServer', x=186.50, y=67.00, z=263.50], EntitySpider['Spider'/5726, l='MpServer', x=296.00, y=34.00, z=334.00], EntityChicken['Chicken'/95, l='MpServer', x=189.50, y=67.00, z=260.50], EntityChicken['Chicken'/96, l='MpServer', x=186.50, y=68.00, z=259.50], EntitySkeleton['Skeleton'/5728, l='MpServer', x=219.50, y=24.00, z=255.50], EntityChicken['Chicken'/97, l='MpServer', x=185.50, y=69.00, z=258.50], EntityZombie['Zombie'/5729, l='MpServer', x=218.50, y=24.00, z=257.50], EntitySkeleton['Skeleton'/5985, l='MpServer', x=229.50, y=37.00, z=268.50], EntityItem['item.tile.mushroom'/100, l='MpServer', x=212.08, y=11.00, z=219.93], EntityRabbit['Rabbit'/101, l='MpServer', x=213.50, y=64.00, z=295.50], EntityRabbit['Rabbit'/102, l='MpServer', x=206.93, y=65.00, z=286.53], EntityCow['Cow'/103, l='MpServer', x=219.50, y=72.00, z=340.50], EntityCow['Cow'/104, l='MpServer', x=218.50, y=72.00, z=342.50], EntityCow['Cow'/105, l='MpServer', x=223.35, y=72.00, z=338.84], EntityCow['Cow'/106, l='MpServer', x=221.36, y=72.00, z=340.30], EntityChicken['Chicken'/111, l='MpServer', x=270.74, y=71.00, z=230.88], EntityChicken['Chicken'/112, l='MpServer', x=267.47, y=71.00, z=235.80], EntityChicken['Chicken'/113, l='MpServer', x=271.19, y=71.00, z=227.91], EntityChicken['Chicken'/114, l='MpServer', x=273.21, y=71.00, z=230.44], EntityZombie['Zombie'/3954, l='MpServer', x=219.50, y=17.00, z=304.50], EntityCow['Cow'/115, l='MpServer', x=276.50, y=74.00, z=333.50], EntitySkeleton['Skeleton'/5235, l='MpServer', x=177.23, y=33.00, z=205.50], EntityCow['Cow'/116, l='MpServer', x=277.50, y=74.00, z=332.50], EntityCow['Cow'/117, l='MpServer', x=276.50, y=73.00, z=330.50], EntityCow['Cow'/118, l='MpServer', x=276.50, y=73.00, z=331.50], EntityCow['Cow'/121, l='MpServer', x=279.50, y=72.00, z=352.82], EntityChicken['Chicken'/127, l='MpServer', x=292.85, y=70.00, z=232.17], EntityChicken['Chicken'/128, l='MpServer', x=297.50, y=72.00, z=220.50], EntityChicken['Chicken'/129, l='MpServer', x=306.12, y=71.00, z=226.55], EntitySpider['Spider'/6017, l='MpServer', x=215.50, y=46.00, z=297.50], EntityChicken['Chicken'/130, l='MpServer', x=301.50, y=71.00, z=217.50], EntityChicken['Chicken'/131, l='MpServer', x=305.50, y=63.00, z=302.50], EntityChicken['Chicken'/132, l='MpServer', x=304.50, y=64.00, z=303.50], EntityChicken['Chicken'/133, l='MpServer', x=305.52, y=72.00, z=312.21], EntityPlayerSP['Joseph_da_IT_Guy'/2240, l='MpServer', x=244.50, y=70.00, z=275.37], EntityChicken['Chicken'/134, l='MpServer', x=300.50, y=65.00, z=304.50], EntityCreeper['Creeper'/4492, l='MpServer', x=214.50, y=15.00, z=217.50], EntitySkeleton['Skeleton'/5516, l='MpServer', x=204.50, y=17.00, z=302.50], EntitySkeleton['Skeleton'/5774, l='MpServer', x=211.50, y=28.00, z=227.50], EntityCreeper['Creeper'/6031, l='MpServer', x=209.17, y=20.00, z=283.53], EntityZombie['Zombie'/6032, l='MpServer', x=212.50, y=20.00, z=284.50], EntityCreeper['Creeper'/6033, l='MpServer', x=209.45, y=20.00, z=281.83], EntityBat['Bat'/3988, l='MpServer', x=234.56, y=55.10, z=277.16], EntityZombie['Zombie'/4245, l='MpServer', x=247.50, y=18.00, z=336.50], EntityItem['item.tile.mushroom'/2966, l='MpServer', x=231.28, y=57.00, z=308.32], EntitySpider['Spider'/4769, l='MpServer', x=311.50, y=49.00, z=208.50], EntityBat['Bat'/5809, l='MpServer', x=217.90, y=21.06, z=289.71], EntityItem['item.tile.gravel'/2228, l='MpServer', x=212.59, y=26.00, z=265.33], EntityBat['Bat'/5814, l='MpServer', x=226.25, y=42.37, z=280.33], EntityBat['Bat'/6070, l='MpServer', x=266.25, y=22.08, z=287.25], EntityZombie['Zombie'/5305, l='MpServer', x=306.50, y=43.00, z=198.50], EntityBat['Bat'/6075, l='MpServer', x=211.30, y=59.04, z=257.28], EntityZombie['Zombie'/4285, l='MpServer', x=277.50, y=63.00, z=221.50], EntitySkeleton['Skeleton'/5822, l='MpServer', x=311.50, y=13.00, z=287.50], EntitySkeleton['Skeleton'/5823, l='MpServer', x=312.50, y=13.00, z=290.50], EntityBat['Bat'/6079, l='MpServer', x=246.69, y=12.08, z=285.36], EntityBat['Bat'/6080, l='MpServer', x=250.63, y=12.02, z=287.50], EntityBat['Bat'/5063, l='MpServer', x=233.25, y=45.10, z=284.25], EntityCreeper['Creeper'/5329, l='MpServer', x=199.50, y=43.00, z=247.50], EntityZombie['Zombie'/4306, l='MpServer', x=224.49, y=38.00, z=277.20], EntityBat['Bat'/3285, l='MpServer', x=228.52, y=26.57, z=288.40], EntityBat['Bat'/3286, l='MpServer', x=222.65, y=35.49, z=283.43], EntityBat['Bat'/5593, l='MpServer', x=239.44, y=52.63, z=312.10], EntityBat['Bat'/5594, l='MpServer', x=229.70, y=56.07, z=320.08], EntityCreeper['Creeper'/5342, l='MpServer', x=242.50, y=52.00, z=310.50], EntityCreeper['Creeper'/5862, l='MpServer', x=247.50, y=25.00, z=307.50], EntityBat['Bat'/3825, l='MpServer', x=288.75, y=23.10, z=338.25], EntityCreeper['Creeper'/5878, l='MpServer', x=251.50, y=44.00, z=285.50], EntityCreeper['Creeper'/5879, l='MpServer', x=246.49, y=42.00, z=288.03], EntityItem['item.tile.mushroom'/3068, l='MpServer', x=230.44, y=54.00, z=314.40], EntitySkeleton['Skeleton'/4861, l='MpServer', x=226.50, y=51.00, z=345.50], EntitySkeleton['Skeleton'/4862, l='MpServer', x=226.50, y=51.00, z=344.50], EntityItem['item.item.seeds'/3071, l='MpServer', x=274.36, y=63.00, z=292.22]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 623323088 bytes (594 MB) / 1107296256 bytes (1056 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version           | Source                        | Signature |
	|:------ |:--------- |:----------------- |:----------------------------- |:--------- |
	| LCHIJA | minecraft | 1.12.2            | minecraft.jar                 | None      |
	| LCHIJA | mcp       | 9.42              | minecraft.jar                 | None      |
	| LCHIJA | FML       | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | forge     | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | hbm       | hbm-1.3.7A-1.12.2 | hbm-1.3.7.1a.jar              | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz

I hope you can solve it.

**Comment by Drillgon200** [comment]
I guess trying to use an access transformer didn't work. Reflection it is then.

**Comment by Drillgon200** [comment]
Don't pause the game while looking at a keypad for now, I'll fix it soon.

**Comment by Joey-Destroyah** [comment]
Also, can you add sound effects to the new blast doors? like entering the password?

**Comment by Drillgon200** [comment]
I'd love to, but I still need to learn how to make custom sounds. I know pretty much nothing about that right now.
