### ISSUE TITLE
The game causes UNU parts pack for immersive vehicles to crash.

### ISSUE THREAD

**Issue by FinnIGuess** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#29]
This mod caused UNU parts pack for immersive vehicles to crash.
[crash-2020-10-12_12.04.56-client.txt](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/5367055/crash-2020-10-12_12.04.56-client.txt) here is the crash report

**Comment by Drillgon200** [comment]
Did you open an issue with them? It's most likely their fault for registering items weirdly. I'll put in a check for it anyway.
