### ISSUE TITLE
Opening launch pad crashes game

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#3]
java.lang.RuntimeException: Slot 6 not in valid range - [0,6)

**Comment by Drillgon200** [comment]
Can you put a full stack trace?

**Comment by TheForge129** [comment]
at net.minecraft.world.World.func_72939_s(World.java:1737)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Buncker
	All players: 1 total; [EntityPlayerMP['TheForge129'/305, l='Buncker', x=-12.63, y=74.20, z=294.70]]
	Chunk stats: ServerChunkCache: 1089 Drop: 0
	Level seed: -516626828
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (120,64,256), Chunk: (at 8,4,0 in 7,16; contains blocks 112,0,256 to 127,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 489861 game time, 489861 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 30551 (now: false), thunder time: 69455 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1371316384 bytes (1307 MB) / 5368709120 bytes (5120 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID               | Version                     | Source                                      | Signature                                |
	|:------ |:---------------- |:--------------------------- |:------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft        | 1.12.2                      | minecraft.jar                               | None                                     |
	| LCHIJA | mcp              | 9.42                        | minecraft.jar                               | None                                     |
	| LCHIJA | FML              | 8.0.99.99                   | forge-1.12.2-14.23.5.2847.jar               | None                                     |
	| LCHIJA | forge            | 14.23.5.2847                | forge-1.12.2-14.23.5.2847.jar               | None                                     |
	| LCHIJA | obfuscate        | 0.2.6                       | minecraft.jar                               | None                                     |
	| LCHIJA | securitycraft    | v1.8.19                     | [1.12.2]+SecurityCraft+v1.8.19.jar          | None                                     |
	| LCHIJA | uncraftingtable  | 1.8-beta6                   | [1.12]UncraftingTable-1.8-beta6.jar         | None                                     |
	| LCHIJA | atg              | 2                           | atg-1.12.2-2.5.0.jar                        | None                                     |
	| LCHIJA | backpack         | 3.0.2                       | backpack-3.0.2-1.12.2.jar                   | None                                     |
	| LCHIJA | blockcraftery    | 1.12.2-1.1.0                | Blockcraftery-Mod-1.12.2.jar                | None                                     |
	| LCHIJA | cdm              | 0.4.1                       | cdm-0.4.1-mc1.12.2.jar                      | None                                     |
	| LCHIJA | cgm              | 0.15.3                      | cgm-0.15.3-mc1.12.2.jar                     | None                                     |
	| LCHIJA | ctm              | MC1.12.2-1.0.2.31           | CTM-MC1.12.2-1.0.2.31.jar                   | None                                     |
	| LCHIJA | jei              | 4.15.0.293                  | jei_1.12.2-4.15.0.293.jar                   | None                                     |
	| LCHIJA | chisel           | MC1.12.2-1.0.2.45           | Chisel-MC1.12.2-1.0.2.45.jar                | None                                     |
	| LCHIJA | redstoneflux     | 2.1.1                       | RedstoneFlux-1.12-2.1.1.1-universal.jar     | None                                     |
	| LCHIJA | cofhcore         | 4.6.6                       | CoFHCore-1.12.2-4.6.6.1-universal.jar       | None                                     |
	| LCHIJA | extendedrenderer | v1.0                        | coroutil-1.12.1-1.2.37.jar                  | None                                     |
	| LCHIJA | coroutil         | 1.12.1-1.2.37               | coroutil-1.12.1-1.2.37.jar                  | None                                     |
	| LCHIJA | configmod        | v1.0                        | coroutil-1.12.1-1.2.37.jar                  | None                                     |
	| LCHIJA | disenchanter     | 1.6                         | disenchanter-[1.12]1.6.jar                  | None                                     |
	| LCHIJA | essentials       | 1.12.2-1.2.1                | essentials-1.12.2-1.2.1.jar                 | None                                     |
	| LCHIJA | extrautils2      | 1.0                         | ExtraUtilities2.jar                         | None                                     |
	| LCHIJA | ezstorage        | 2.5.0                       | ezstorage-2.5.0-[1.12.2].jar                | None                                     |
	| LCHIJA | filteredhopper   | 2.1.1                       | filteredhopper-2.1.1.jar                    | None                                     |
	| LCHIJA | cfm              | 6.3.1                       | furniture-6.3.1-1.12.2.jar                  | None                                     |
	| LCHIJA | ghostsexplosives | 2.0.0 - MC 1.12.2           | Ghosts-Explosives-Mod-1.12.2.jar            | None                                     |
	| LCHIJA | hbm              | hbm-1.3.4A-1.12.2           | hbm-1.3.4a-1.12.2.jar                       | None                                     |
	| LCHIJA | hopperducts      | 1.5                         | hopperducts-mc1.12-1.5.jar                  | None                                     |
	| LCHIJA | infinitefluids   | 1.2.0                       | infinitefluids-1.11-1.2.0.jar               | None                                     |
	| LCHIJA | malisiscore      | 1.12.2-6.5.1-SNAPSHOT       | malisiscore-1.12.2-6.5.1.jar                | None                                     |
	| LCHIJA | malisisdoors     | 1.12.2-7.3.0                | malisisdoors-1.12.2-7.3.0.jar               | None                                     |
	| LCHIJA | millenaire       | Millénaire 8.1.0            | millenaire-8.1.0.jar                        | None                                     |
	| LCHIJA | mmdlib           | 1.0.0-rc2                   | mmdlib.jar                                  | None                                     |
	| LCHIJA | mumboredstone    | 0.3.3                       | mumboredstone-0.3.3.jar                     | None                                     |
	| LCHIJA | nethermetals     | 1.2.0-rc2                   | NetherMetals-1.12-1.2.0-rc2.76.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | notchapplerecipe | 1.0.0                       | NotchAppleRecipe1.12.2.jar                  | None                                     |
	| LCHIJA | sandro           | 1.3d                        | Redstone+++ver1.3e.jar                      | None                                     |
	| LCHIJA | redstoneplusplus | 1.3e                        | Redstone+++ver1.3e.jar                      | None                                     |
	| LCHIJA | respawnablepets  | 1.0.4.2                     | Respawnable-Pets-Mod-1.12.2.jar             | None                                     |
	| LCHIJA | frftl            | 1.0.0                       | RottenFleshToLeather1.12.2.jar              | None                                     |
	| LCHIJA | simple_orez      | 1.0.0                       | SimpleOrez-0.2.0a.jar                       | None                                     |
	| LCHIJA | smarthoppers     | 4.1.5                       | smarthoppers-mc1.12.2-4.1.5.jar             | None                                     |
	| LCHIJA | supertnt         | 1.0.1                       | SuperTNT-1.12.2-1.0.1.jar                   | None                                     |
	| LCHIJA | thutcore         | 5.21.0                      | thutcore-1.12.2-5.21.0.jar                  | None                                     |
	| LCHIJA | thutcore_compat  | 1.0                         | thutcore-1.12.2-5.21.0.jar                  | None                                     |
	| LCHIJA | thuttech         | 6.1.6                       | thuttech-1.12.2-6.1.6.jar                   | None                                     |
	| LCHIJA | uppers           | 0.0.6                       | Uppers-0.0.6.jar                            | None                                     |
	| LCHIJA | vbe              | GRADLE:VERSION-GRADLE:BUILD | Vanilla+Builders+Extension-1.12.2-1.0.9.jar | None                                     |
	| LCHIJA | weather2         | 1.12.1-2.6.12               | weather2-1.12.1-2.6.12.jar                  | None                                     |
	| LCHIJA | wit              | 1.0.25                      | WIT-1.12-1.0.25-44.jar                      | None                                     |
	| LCHIJA | xaeroworldmap    | 1.6.1                       | XaerosWorldMap_1.6.1_Forge_1.12.jar         | None                                     |
	| LCHIJA | mysticallib      | 1.12.2-1.6.0                | MysticalLib-1.12.2.jar                      | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['TheForge129'/305, l='Buncker', x=-12.63, y=74.20, z=294.70]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 446.14
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by TheForge129** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 7/21/20 6:12 PM
Description: Ticking player

java.lang.RuntimeException: Slot 6 not in valid range - [0,6)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:214)
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:73)
	at net.minecraftforge.items.SlotItemHandler.func_75211_c(SlotItemHandler.java:73)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:79)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1737)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:214)
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:73)
	at net.minecraftforge.items.SlotItemHandler.func_75211_c(SlotItemHandler.java:73)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:79)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 305
	Entity Name: TheForge129
	Entity's Exact location: -12.63, 74.20, 294.70
	Entity's Block location: World: (-13,74,294), Chunk: (at 3,4,6 in -1,18; contains blocks -16,0,288 to -1,255,303), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1737)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Buncker
	All players: 1 total; [EntityPlayerMP['TheForge129'/305, l='Buncker', x=-12.63, y=74.20, z=294.70]]
	Chunk stats: ServerChunkCache: 1089 Drop: 0
	Level seed: -516626828
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (120,64,256), Chunk: (at 8,4,0 in 7,16; contains blocks 112,0,256 to 127,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 489861 game time, 489861 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 30551 (now: false), thunder time: 69455 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1371316384 bytes (1307 MB) / 5368709120 bytes (5120 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID               | Version                     | Source                                      | Signature                                |
	|:------ |:---------------- |:--------------------------- |:------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft        | 1.12.2                      | minecraft.jar                               | None                                     |
	| LCHIJA | mcp              | 9.42                        | minecraft.jar                               | None                                     |
	| LCHIJA | FML              | 8.0.99.99                   | forge-1.12.2-14.23.5.2847.jar               | None                                     |
	| LCHIJA | forge            | 14.23.5.2847                | forge-1.12.2-14.23.5.2847.jar               | None                                     |
	| LCHIJA | obfuscate        | 0.2.6                       | minecraft.jar                               | None                                     |
	| LCHIJA | securitycraft    | v1.8.19                     | [1.12.2]+SecurityCraft+v1.8.19.jar          | None                                     |
	| LCHIJA | uncraftingtable  | 1.8-beta6                   | [1.12]UncraftingTable-1.8-beta6.jar         | None                                     |
	| LCHIJA | atg              | 2                           | atg-1.12.2-2.5.0.jar                        | None                                     |
	| LCHIJA | backpack         | 3.0.2                       | backpack-3.0.2-1.12.2.jar                   | None                                     |
	| LCHIJA | blockcraftery    | 1.12.2-1.1.0                | Blockcraftery-Mod-1.12.2.jar                | None                                     |
	| LCHIJA | cdm              | 0.4.1                       | cdm-0.4.1-mc1.12.2.jar                      | None                                     |
	| LCHIJA | cgm              | 0.15.3                      | cgm-0.15.3-mc1.12.2.jar                     | None                                     |
	| LCHIJA | ctm              | MC1.12.2-1.0.2.31           | CTM-MC1.12.2-1.0.2.31.jar                   | None                                     |
	| LCHIJA | jei              | 4.15.0.293                  | jei_1.12.2-4.15.0.293.jar                   | None                                     |
	| LCHIJA | chisel           | MC1.12.2-1.0.2.45           | Chisel-MC1.12.2-1.0.2.45.jar                | None                                     |
	| LCHIJA | redstoneflux     | 2.1.1                       | RedstoneFlux-1.12-2.1.1.1-universal.jar     | None                                     |
	| LCHIJA | cofhcore         | 4.6.6                       | CoFHCore-1.12.2-4.6.6.1-universal.jar       | None                                     |
	| LCHIJA | extendedrenderer | v1.0                        | coroutil-1.12.1-1.2.37.jar                  | None                                     |
	| LCHIJA | coroutil         | 1.12.1-1.2.37               | coroutil-1.12.1-1.2.37.jar                  | None                                     |
	| LCHIJA | configmod        | v1.0                        | coroutil-1.12.1-1.2.37.jar                  | None                                     |
	| LCHIJA | disenchanter     | 1.6                         | disenchanter-[1.12]1.6.jar                  | None                                     |
	| LCHIJA | essentials       | 1.12.2-1.2.1                | essentials-1.12.2-1.2.1.jar                 | None                                     |
	| LCHIJA | extrautils2      | 1.0                         | ExtraUtilities2.jar                         | None                                     |
	| LCHIJA | ezstorage        | 2.5.0                       | ezstorage-2.5.0-[1.12.2].jar                | None                                     |
	| LCHIJA | filteredhopper   | 2.1.1                       | filteredhopper-2.1.1.jar                    | None                                     |
	| LCHIJA | cfm              | 6.3.1                       | furniture-6.3.1-1.12.2.jar                  | None                                     |
	| LCHIJA | ghostsexplosives | 2.0.0 - MC 1.12.2           | Ghosts-Explosives-Mod-1.12.2.jar            | None                                     |
	| LCHIJA | hbm              | hbm-1.3.4A-1.12.2           | hbm-1.3.4a-1.12.2.jar                       | None                                     |
	| LCHIJA | hopperducts      | 1.5                         | hopperducts-mc1.12-1.5.jar                  | None                                     |
	| LCHIJA | infinitefluids   | 1.2.0                       | infinitefluids-1.11-1.2.0.jar               | None                                     |
	| LCHIJA | malisiscore      | 1.12.2-6.5.1-SNAPSHOT       | malisiscore-1.12.2-6.5.1.jar                | None                                     |
	| LCHIJA | malisisdoors     | 1.12.2-7.3.0                | malisisdoors-1.12.2-7.3.0.jar               | None                                     |
	| LCHIJA | millenaire       | Millénaire 8.1.0            | millenaire-8.1.0.jar                        | None                                     |
	| LCHIJA | mmdlib           | 1.0.0-rc2                   | mmdlib.jar                                  | None                                     |
	| LCHIJA | mumboredstone    | 0.3.3                       | mumboredstone-0.3.3.jar                     | None                                     |
	| LCHIJA | nethermetals     | 1.2.0-rc2                   | NetherMetals-1.12-1.2.0-rc2.76.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | notchapplerecipe | 1.0.0                       | NotchAppleRecipe1.12.2.jar                  | None                                     |
	| LCHIJA | sandro           | 1.3d                        | Redstone+++ver1.3e.jar                      | None                                     |
	| LCHIJA | redstoneplusplus | 1.3e                        | Redstone+++ver1.3e.jar                      | None                                     |
	| LCHIJA | respawnablepets  | 1.0.4.2                     | Respawnable-Pets-Mod-1.12.2.jar             | None                                     |
	| LCHIJA | frftl            | 1.0.0                       | RottenFleshToLeather1.12.2.jar              | None                                     |
	| LCHIJA | simple_orez      | 1.0.0                       | SimpleOrez-0.2.0a.jar                       | None                                     |
	| LCHIJA | smarthoppers     | 4.1.5                       | smarthoppers-mc1.12.2-4.1.5.jar             | None                                     |
	| LCHIJA | supertnt         | 1.0.1                       | SuperTNT-1.12.2-1.0.1.jar                   | None                                     |
	| LCHIJA | thutcore         | 5.21.0                      | thutcore-1.12.2-5.21.0.jar                  | None                                     |
	| LCHIJA | thutcore_compat  | 1.0                         | thutcore-1.12.2-5.21.0.jar                  | None                                     |
	| LCHIJA | thuttech         | 6.1.6                       | thuttech-1.12.2-6.1.6.jar                   | None                                     |
	| LCHIJA | uppers           | 0.0.6                       | Uppers-0.0.6.jar                            | None                                     |
	| LCHIJA | vbe              | GRADLE:VERSION-GRADLE:BUILD | Vanilla+Builders+Extension-1.12.2-1.0.9.jar | None                                     |
	| LCHIJA | weather2         | 1.12.1-2.6.12               | weather2-1.12.1-2.6.12.jar                  | None                                     |
	| LCHIJA | wit              | 1.0.25                      | WIT-1.12-1.0.25-44.jar                      | None                                     |
	| LCHIJA | xaeroworldmap    | 1.6.1                       | XaerosWorldMap_1.6.1_Forge_1.12.jar         | None                                     |
	| LCHIJA | mysticallib      | 1.12.2-1.6.0                | MysticalLib-1.12.2.jar                      | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['TheForge129'/305, l='Buncker', x=-12.63, y=74.20, z=294.70]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 446.14
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by Drillgon200** [comment]
Hmm, that shouldn't be happening. All the launch pads have 8 slots. Did the launch pad exist before the latest update?

**Comment by TheForge129** [comment]
Yes, it has existed for a while
it has existed since the new missiles were added

**Comment by Drillgon200** [comment]
Ok well try breaking and replacing it. If it was placed before the latest update that would explain the crash.

**Comment by TheForge129** [comment]
ooohhhhhhhhh

thanks :/
