### ISSUE TITLE
IDEA: Hacking the blast doors

### ISSUE THREAD

**Issue by MAX2136** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#31]
IDEA: Hacking the blast doors
Basically, a hacking device used to hack blast doors (sliding w/keypad)
Could be used to stealthily open these (when you're not supposed to)
Sry if this is stupid, then just close it

**Comment by Drillgon200** [comment]
No, that's a good idea. Like an alternative for picking a lock for keypads or something. I don't know how to make it interesting though.

**Comment by MAX2136** [comment]
Maybe a minigame?
Or MKII version for lazy people, who just want to open it?

**Comment by Drillgon200** [comment]
I'd have to think of a good minigame though, and I can't think of one interesting or challenging enough to actually keep people out of your base without them trivially bypassing your doors.

**Comment by MAX2136** [comment]
Well,
It would still be cool
But it's your mod fork, so do as you want

**Comment by Drillgon200** [comment]
Well I don't want to make it bad, like cut 3 wires or something.

**Comment by MAX2136** [comment]
Well
lockpicking is just clicking and hoping it's going to work
sooo (no offense)

**Comment by MAX2136** [comment]
And one more quesion, will you make the Vault-tec blast door with a keypad?
(variant, no replacement)

**Comment by MAX2136** [comment]
Oh and horizontal doors would be nice (sliding blast door but horizontal)
And 4 high ones as well

**Comment by MAX2136** [comment]
Sry if i am asking too much
