### ISSUE TITLE
[Suggestion] Unlimite the HE-RF converter

### ISSUE THREAD

**Issue by NanJack1998** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#32]
Hello,
    I tried to make my own modpack with HBM,flux network,draconic evolution and mekanism in a 1.12.2 version.
    In curious i want to figure out how fast can a AMS reactor fullfill an 8th level draconic's energy core(it can contain 2^31 - 1 RF),now i've made a try in creative mod but the limit of the HE converter stop me from fastly fullfill the energy core.
    So if there's a way to unlimit the converter so that i can finish my test?

**Comment by Drillgon200** [comment]
That might be a good idea. I might add this at some point.

**Comment by NanJack1998** [comment]
thank you

**Comment by Drillgon200** [comment]
Well, it can't be infinite due to limitations of both the RF and HE systems, but bob improved this in 1.7.10 so it'll be as close as it gets in the next update.
