### ISSUE TITLE
[Crash] issue with Survival Inc. mod

### ISSUE THREAD

**Issue by gatoborrachon** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#34]
**Short Description**
When the game tries to render your body when you are a ghost (feature from Surival Inc.), the game crashes

**To Reproduce**
1. Play with HBM's Nuclear Tech Mod and Survival Inc.
2. Die
3. Press "E" or "F5"

**Crash Report**
https://pastebin.com/PdvPbYG0

**Additional Notes**
HBM's Nuclear Tech Mod version: 1.3.7.1a.
Survival Inc. version: 1.2.0

the developer of Survival Inc. said this:
> EDIT: Okay I had a quick look on the source you have linked (really thanks for that!), but the actual conflicting code seems to be on [Line 1152](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/blob/1.12.2_test/com/hbm/main/ModEventHandlerClient.java#L1152) in method preRenderLiving. They're basically assuming that everything that renders player as EntityLivingBase uses RenderPlayer (see the cast to RenderPlayer on that line). This is assumption may be true for vanilla, but not for anything that replaces the default player renderer (RenderPlayer). Looking at the code, it should behave exactly the same if they had used just RenderLivingBase instead of RenderPlayer (i.e. the RenderPlayer cast is an unnecessary assumption leading to errors like this).

Link to the issue: https://github.com/Enginecrafter77/SurvivalInc/issues/23

**Comment by Enginecrafter77** [comment]
Also, to clarify. I was wrong about the thing with just removing the cast from preRenderLiving. The whole code was dependant on ModelPlayer (which is only provided by RenderPlayer), so I moved it into preRenderPlayer method in the PR. The updated code was tested against https://github.com/Enginecrafter77/SurvivalInc/commit/0cf5a2b59576741e18f6fe902dddb0501a0609ec and everything works as expected.
