### ISSUE TITLE
装配机模板错误

### ISSUE THREAD

**Issue by Pok08** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#37]
在装配机放入模板会导致所有材料需求变为1

**Comment by UFFR** [comment]
A similar issue has been solved before, can you explain further to see 
if it's the same or a different one?

-- 
UFFR

**Comment by Drillgon200** [comment]
I think this is fixed in dev, though I'll go check again.

**Comment by Drillgon200** [comment]
It should have only happened when chests were used to fill the assembler though. It looks like all those cases are accounted for in code, and I can't replicate it, so I'll close this issue. Reopen if it still happens after the next update.
