### ISSUE TITLE
it's been a while

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#38]
I can't seem to get the particle accelerator to work... I built it right, I even used the weakest magnets, but it always explodes instantly

**Comment by Drillgon200** [comment]
Show build.

**Comment by TheForge129** [comment]
Have to build a new one due to blowing it up to test the new nuke fx with sildur's shaders
Also, the plasma heater doesn't seem to turn into the machine even when i place the parts in the right spot, i have yet to test this with the fusion reactor

**Comment by TheForge129** [comment]
aight, here you go
sorry about the hotbar, my f1 key isn't turning it off fsr
![image](https://user-images.githubusercontent.com/67129496/104012589-aec37280-5175-11eb-94cb-430764a524cd.png)
![image](https://user-images.githubusercontent.com/67129496/104012567-a79c6480-5175-11eb-93dd-76e59f0f2754.png)
![image](https://user-images.githubusercontent.com/67129496/104012616-be42bb80-5175-11eb-91d6-f3ffd863a476.png)
![image](https://user-images.githubusercontent.com/67129496/104012628-c3076f80-5175-11eb-8b41-f80b422841a5.png)
![image](https://user-images.githubusercontent.com/67129496/104012642-ca2e7d80-5175-11eb-9281-550946c3717c.png)

**Comment by UFFR** [comment]
I think it's because that recipe you're using requires an "analysis 
chamber" or whatever it's called.

-- 
UFFR

**Comment by TheForge129** [comment]
i made one

**Comment by UFFR** [comment]
And you're sure it's set up properly? Or perhaps your accelerator needs 
to be larger as a whole.

On 1/9/21 4:58 PM, TheForge129 wrote:
> i made one 

-- 
UFFR

**Comment by TheForge129** [comment]
hydrogen, copper > positron and antiproton requires 160 coil strength, mine is big enough

**Comment by Drillgon200** [comment]
That accelerator core doesn't look like it's pointing the right way. Other people have managed to build this fine, so you must be doing something wrong.

About the plasma heater, darn, I thought I had fixed that one.

**Comment by TheForge129** [comment]
ah, that makes sense

**Comment by Drillgon200** [comment]
Alright, fixed plasma heater. Was offsetting in the wrong place.

**Comment by Drillgon200** [comment]
![2021-01-10_19 02 01](https://user-images.githubusercontent.com/50186362/104143984-73dc5d00-5376-11eb-85da-f94260de95a2.png)
The thing should still work, you just have to build it like this.
