### ISSUE TITLE
numero dos

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#39]
shredding blocks/ingots to powder doesn't work at all, the recipes are missing

**Comment by TheForge129** [comment]
sidenote: you should test each release more as i don't understand how something essential to the mod being completely broken was overlooked

**Comment by Drillgon200** [comment]
I'm not going to test every single feature every time I make a release. I probably just shredded one item that actually worked, and shredding every recipe would take way too long.

**Comment by TheForge129** [comment]
The thing is, it doesn't even show the recipe on JEI

**Comment by Drillgon200** [comment]
Yeah, because it's not registered. Shredder recipes were registered before NTM's ore dictionary, so it would have worked with any mod that does ore dict register in pre init.

**Comment by TheForge129** [comment]
You are actually correct about the ore dict pre init thing, as extra utilities 2 has some of the recipes. However, i don't think it works for the ingots, blocks, and ores that don't use ore dictionary

Approximately how much time would it take to fix this issue? Asking b/c it's not fixed in 1.4.1
