### ISSUE TITLE
Crash when mining galacticraftplanets blocks with the "worker's alloy pickaxe"

### ISSUE THREAD

**Issue by someonestupid4524** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#43]
here is the crash report, the crash (of the server) happens only when im mining desh ore (galacticraft) with the silk touch option of the worker's alloy pickaxe, wich is made of desh (hbm)

[crash-2021-01-19_19.21.08-server.txt](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/5837921/crash-2021-01-19_19.21.08-server.txt)

**Comment by someonestupid4524** [comment]
it doesnt crash with any other pickaxe, only that one and its very annoying

**Comment by Drillgon200** [comment]
Not the only problem with galacticraft in any case. I'll test it when I get to the bug with fluids.

**Comment by Drillgon200** [comment]
Can't replicate, going to assume I fixed it. Reopen if not.
