### ISSUE TITLE
Game crashing whenever I open the Satellite Control Interface

### ISSUE THREAD

**Issue by Cattoland** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#45]
Minecraft just seems to crash whenever I try to right click the Satellite Control Interface, which is quite an important part of the mod. Here is a list of my mods: https://prnt.sc/xm49pr

The crash log is here:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittlePatchingLoader (LittleTiles_v1.5.0-pre320_mc1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  CreativePatchingLoader (CreativeCore_v1.10.44_mc1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  weaponlib (mw_2.0-0.4.6.2_mc1.12.2 (1).jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192 (2).jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 1/25/21 5:29 PM
Description: Rendering screen

java.lang.IllegalArgumentException: Stack can not be invalid!
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:504)
	at com.hbm.inventory.gui.GUIScreenSatInterface.isOre(GUIScreenSatInterface.java:241)
	at com.hbm.inventory.gui.GUIScreenSatInterface.getColorFromBlock(GUIScreenSatInterface.java:236)
	at com.hbm.inventory.gui.GUIScreenSatInterface.drawScan(GUIScreenSatInterface.java:176)
	at com.hbm.inventory.gui.GUIScreenSatInterface.drawGuiContainerBackgroundLayer(GUIScreenSatInterface.java:128)
	at com.hbm.inventory.gui.GUIScreenSatInterface.func_73863_a(GUIScreenSatInterface.java:70)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:504)
	at com.hbm.inventory.gui.GUIScreenSatInterface.isOre(GUIScreenSatInterface.java:241)
	at com.hbm.inventory.gui.GUIScreenSatInterface.getColorFromBlock(GUIScreenSatInterface.java:236)
	at com.hbm.inventory.gui.GUIScreenSatInterface.drawScan(GUIScreenSatInterface.java:176)
	at com.hbm.inventory.gui.GUIScreenSatInterface.drawGuiContainerBackgroundLayer(GUIScreenSatInterface.java:128)
	at com.hbm.inventory.gui.GUIScreenSatInterface.func_73863_a(GUIScreenSatInterface.java:70)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: com.hbm.inventory.gui.GUIScreenSatInterface
	Mouse location: Scaled: (320, 169). Absolute: (960, 508)
	Screen size: Scaled: (640, 339). Absolute: (1920, 1017). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Ventosity'/1881, l='MpServer', x=54.50, y=93.00, z=-259.47]]
	Chunk stats: MultiplayerChunkCache: 168, 168
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (148,64,-160), Chunk: (at 4,4,0 in 9,-10; contains blocks 144,0,-160 to 159,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 39748 game time, 39748 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 121 total; [EntityPig['Pig'/13, l='MpServer', x=29.48, y=86.00, z=-198.75], EntityPig['Pig'/14, l='MpServer', x=30.50, y=81.00, z=-202.50], EntityPig['Pig'/15, l='MpServer', x=31.67, y=80.00, z=-206.50], EntityPig['Pig'/16, l='MpServer', x=36.50, y=81.00, z=-201.37], EntityPig['Pig'/17, l='MpServer', x=34.53, y=85.00, z=-189.25], EntityPig['Pig'/18, l='MpServer', x=21.73, y=86.00, z=-196.64], EntityPig['Pig'/19, l='MpServer', x=29.46, y=87.00, z=-189.25], EntityPig['Pig'/20, l='MpServer', x=24.49, y=88.00, z=-190.68], EntityPig['Pig'/33, l='MpServer', x=129.21, y=82.00, z=-279.46], EntityPig['Pig'/34, l='MpServer', x=123.50, y=85.00, z=-273.50], EntityPig['Pig'/35, l='MpServer', x=123.50, y=85.00, z=-273.50], EntityPig['Pig'/36, l='MpServer', x=114.55, y=87.00, z=-275.94], EntityBat['Bat'/14496, l='MpServer', x=95.50, y=29.10, z=-336.50], EntityZombie['Zombie'/14497, l='MpServer', x=91.50, y=83.00, z=-338.50], EntityZombie['Zombie'/14536, l='MpServer', x=-19.50, y=65.00, z=-215.50], EntityItem['item.tile.dirt.default'/14795, l='MpServer', x=25.29, y=80.00, z=-207.77], EntityItem['item.tile.dirt.default'/14797, l='MpServer', x=41.36, y=75.00, z=-207.37], EntityItem['item.tile.dirt.default'/14801, l='MpServer', x=11.23, y=87.00, z=-210.11], EntityItem['item.tile.dirt.default'/14802, l='MpServer', x=21.88, y=79.00, z=-209.43], EntityItem['item.tile.dirt.default'/14803, l='MpServer', x=16.77, y=81.00, z=-210.88], EntityItem['item.tile.dirt.default'/14805, l='MpServer', x=25.13, y=79.00, z=-212.13], EntityItem['item.tile.stonebrick'/14807, l='MpServer', x=31.88, y=77.00, z=-211.83], EntityItem['item.tile.stonebrick'/14808, l='MpServer', x=33.68, y=77.00, z=-212.16], EntityItem['item.tile.dirt.default'/14809, l='MpServer', x=13.13, y=85.00, z=-212.42], EntityItem['item.tile.log.birch'/14811, l='MpServer', x=36.98, y=78.00, z=-212.39], EntityItem['item.tile.dirt.default'/14814, l='MpServer', x=42.88, y=59.00, z=-212.17], EntityItem['item.tile.dirt.default'/14816, l='MpServer', x=28.13, y=79.00, z=-214.12], EntityItem['item.tile.stonebrick'/14820, l='MpServer', x=26.88, y=77.00, z=-214.68], EntityItem['item.tile.dirt.default'/14822, l='MpServer', x=18.81, y=80.00, z=-216.75], EntityItem['item.tile.dirt.default'/14823, l='MpServer', x=25.93, y=79.00, z=-215.59], EntityItem['item.tile.dirt.default'/14824, l='MpServer', x=21.03, y=80.00, z=-215.06], EntityItem['item.tile.log.birch'/14825, l='MpServer', x=25.21, y=79.00, z=-216.80], EntityItem['item.tile.dirt.default'/14827, l='MpServer', x=11.13, y=87.00, z=-217.88], EntityItem['item.tile.dirt.default'/14829, l='MpServer', x=30.65, y=77.00, z=-217.29], EntityItem['item.tile.dirt.default'/14830, l='MpServer', x=38.59, y=74.00, z=-217.13], EntityItem['item.tile.dirt.default'/14832, l='MpServer', x=31.49, y=77.00, z=-218.88], EntityItem['item.tile.stonebrick'/14833, l='MpServer', x=31.76, y=77.00, z=-218.88], EntityItem['item.tile.flower2.poppy'/14835, l='MpServer', x=7.58, y=93.00, z=-220.29], EntityItem['item.tile.stonebrick'/14838, l='MpServer', x=11.32, y=87.00, z=-219.47], EntityItem['item.tile.stonebrick'/14839, l='MpServer', x=12.94, y=85.00, z=-219.28], EntityItem['item.tile.dirt.default'/14841, l='MpServer', x=24.59, y=79.00, z=-218.22], EntityItem['item.tile.dirt.default'/14847, l='MpServer', x=16.19, y=81.00, z=-221.88], EntityItem['item.tile.dirt.default'/14848, l='MpServer', x=30.09, y=78.00, z=-221.82], EntityItem['item.tile.dirt.default'/14849, l='MpServer', x=17.13, y=82.00, z=-222.56], EntityItem['item.tile.dirt.default'/14851, l='MpServer', x=23.40, y=80.00, z=-220.87], EntityItem['item.tile.stonebrick'/14852, l='MpServer', x=22.09, y=80.00, z=-222.41], EntityItem['item.tile.dirt.default'/14855, l='MpServer', x=18.27, y=81.00, z=-222.35], EntityItem['item.tile.stonebrick'/14856, l='MpServer', x=14.88, y=83.00, z=-222.88], EntityItem['item.tile.stonebrick'/14859, l='MpServer', x=29.53, y=78.00, z=-223.57], EntityItem['item.tile.dirt.default'/14860, l='MpServer', x=37.13, y=75.00, z=-222.13], EntityItem['item.tile.doublePlant.rose'/14861, l='MpServer', x=11.13, y=92.00, z=-222.75], EntityItem['item.tile.dirt.default'/14862, l='MpServer', x=19.82, y=81.00, z=-224.41], EntityItem['item.tile.dirt.default'/14863, l='MpServer', x=24.48, y=80.00, z=-221.57], EntityItem['item.tile.dirt.default'/14867, l='MpServer', x=34.13, y=77.00, z=-224.28], EntityItem['item.tile.stonebrick'/14869, l='MpServer', x=16.42, y=83.00, z=-224.86], EntityItem['item.tile.dirt.default'/14870, l='MpServer', x=30.24, y=79.00, z=-225.89], EntityItem['item.item.coal'/14872, l='MpServer', x=21.88, y=80.00, z=-224.43], EntityItem['item.tile.dirt.default'/14874, l='MpServer', x=31.00, y=78.00, z=-223.55], EntityItem['item.tile.dirt.default'/14876, l='MpServer', x=38.19, y=74.00, z=-224.13], EntityItem['item.tile.dirt.default'/14877, l='MpServer', x=17.21, y=85.00, z=-224.76], EntityItem['item.tile.stonebrick'/14878, l='MpServer', x=19.13, y=59.00, z=-228.42], EntityItem['item.tile.dirt.default'/14879, l='MpServer', x=33.35, y=79.00, z=-224.83], EntityItem['item.tile.dirt.default'/14882, l='MpServer', x=13.26, y=89.00, z=-226.47], EntityItem['item.tile.dirt.default'/14883, l='MpServer', x=15.24, y=90.00, z=-225.92], EntityItem['item.tile.stonebrick'/14884, l='MpServer', x=17.63, y=84.00, z=-226.46], EntityItem['item.tile.dirt.default'/14885, l='MpServer', x=26.88, y=80.00, z=-227.72], EntityItem['item.tile.doublePlant.rose'/14889, l='MpServer', x=12.95, y=93.00, z=-227.31], EntityItem['item.tile.dirt.default'/14891, l='MpServer', x=20.88, y=59.00, z=-228.89], EntityItem['item.tile.dirt.default'/14893, l='MpServer', x=31.05, y=80.00, z=-228.80], EntityItem['item.tile.dirt.default'/14894, l='MpServer', x=33.13, y=78.00, z=-227.34], EntityItem['item.tile.dirt.default'/14897, l='MpServer', x=17.18, y=90.00, z=-229.31], EntityItem['item.tile.dirt.default'/14898, l='MpServer', x=21.47, y=59.00, z=-231.45], EntityItem['item.tile.dirt.default'/14901, l='MpServer', x=17.88, y=91.00, z=-234.69], EntityItem['item.tile.dirt.default'/14902, l='MpServer', x=30.99, y=89.00, z=-235.82], EntityItem['item.tile.dirt.default'/14904, l='MpServer', x=23.59, y=81.00, z=-203.91], EntityItem['item.tile.dirt.default'/14907, l='MpServer', x=12.61, y=87.00, z=-204.02], EntityItem['item.tile.dirt.default'/14908, l='MpServer', x=19.91, y=83.00, z=-205.14], EntityItem['item.item.mw_SulfurDust'/14909, l='MpServer', x=17.79, y=82.00, z=-207.37], EntityItem['item.tile.dirt.default'/14910, l='MpServer', x=21.92, y=78.00, z=-206.30], EntityItem['item.tile.dirt.default'/14911, l='MpServer', x=28.12, y=80.00, z=-205.85], EntityZombie['Zombie'/12864, l='MpServer', x=131.50, y=17.00, z=-297.50], EntityZombie['Zombie'/12865, l='MpServer', x=131.75, y=45.00, z=-287.56], EntityBat['Bat'/8788, l='MpServer', x=133.19, y=43.02, z=-274.31], EntityItem['item.tile.sapling.birch'/15101, l='MpServer', x=39.13, y=77.00, z=-223.67], EntitySkeleton['Skeleton'/15153, l='MpServer', x=-22.50, y=12.00, z=-338.50], EntityZombie['Zombie'/15154, l='MpServer', x=-22.50, y=12.00, z=-336.50], EntityZombie['Zombie'/15157, l='MpServer', x=-24.50, y=14.00, z=-288.50], EntityItem['item.tile.sapling.birch'/15219, l='MpServer', x=92.88, y=63.00, z=-227.36], EntityZombie['Zombie'/9330, l='MpServer', x=21.53, y=63.00, z=-257.94], EntityCreeper['Creeper'/9347, l='MpServer', x=59.63, y=75.00, z=-259.79], EntityEnderman['Enderman'/9348, l='MpServer', x=60.70, y=75.00, z=-259.74], EntityItem['item.item.porkchopRaw'/11420, l='MpServer', x=65.88, y=62.00, z=-246.59], EntityCreeper['Creeper'/9398, l='MpServer', x=-12.50, y=64.00, z=-340.50], EntitySkeleton['Skeleton'/9400, l='MpServer', x=77.12, y=74.00, z=-269.50], EntityCreeper['Creeper'/9407, l='MpServer', x=130.50, y=35.00, z=-338.50], EntityZombie['Zombie'/9412, l='MpServer', x=-16.50, y=28.00, z=-240.50], EntityWitch['Witch'/9413, l='MpServer', x=-20.50, y=17.00, z=-247.50], EntityPig['Pig'/9414, l='MpServer', x=-18.50, y=72.00, z=-245.50], EntityPig['Pig'/9415, l='MpServer', x=-20.50, y=80.00, z=-244.50], EntityPig['Pig'/9416, l='MpServer', x=-19.50, y=91.00, z=-241.50], EntityPig['Pig'/9417, l='MpServer', x=-19.50, y=91.00, z=-243.50], EntitySkeleton['Skeleton'/9492, l='MpServer', x=91.50, y=30.00, z=-277.50], EntityBat['Bat'/9588, l='MpServer', x=-16.15, y=35.97, z=-331.23], EntityBat['Bat'/9589, l='MpServer', x=-16.08, y=35.99, z=-330.58], EntityBat['Bat'/9591, l='MpServer', x=-20.40, y=18.98, z=-320.24], EntitySkeleton['Skeleton'/9594, l='MpServer', x=-21.50, y=66.00, z=-309.50], EntityPig['Pig'/14081, l='MpServer', x=43.45, y=81.00, z=-311.55], EntityPig['Pig'/14082, l='MpServer', x=47.50, y=79.00, z=-315.50], EntityPig['Pig'/14083, l='MpServer', x=40.69, y=81.00, z=-316.57], EntityPig['Pig'/14084, l='MpServer', x=41.70, y=81.00, z=-312.51], EntityCreeper['Creeper'/14086, l='MpServer', x=97.50, y=30.00, z=-316.50], EntityPig['Pig'/14087, l='MpServer', x=108.50, y=71.00, z=-311.50], EntityPig['Pig'/14088, l='MpServer', x=110.50, y=71.00, z=-309.50], EntityPig['Pig'/14089, l='MpServer', x=103.74, y=71.00, z=-310.49], EntityPig['Pig'/14090, l='MpServer', x=113.28, y=70.00, z=-300.54], EntityCreeper['Creeper'/14091, l='MpServer', x=131.50, y=54.00, z=-315.50], EntityPig['Pig'/14152, l='MpServer', x=-8.53, y=75.00, z=-278.28], EntityPig['Pig'/14153, l='MpServer', x=-4.68, y=75.00, z=-278.48], EntityPig['Pig'/14154, l='MpServer', x=-10.30, y=78.00, z=-273.13], EntityPig['Pig'/14155, l='MpServer', x=-13.34, y=83.00, z=-274.52], EntityPlayerSP['Ventosity'/1881, l='MpServer', x=54.50, y=93.00, z=-259.47]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 221511352 bytes (211 MB) / 3089104896 bytes (2946 MB) up to 3089104896 bytes (2946 MB)
	JVM Flags: 3 total; -Xms3072m -Xmx3072m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                                 | Signature |
	|:------ |:-------------------- |:----------------- |:------------------------------------------------------ |:--------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                          | None      |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                          | None      |
	| LCHIJA | FML                  | 8.0.99.99         | modpack.jar                                            | None      |
	| LCHIJA | forge                | 14.23.5.2847      | modpack.jar                                            | None      |
	| LCHIJA | creativecoredummy    | 1.0.0             | minecraft.jar                                          | None      |
	| LCHIJA | littletilescore      | 1.0.0             | minecraft.jar                                          | None      |
	| LCHIJA | opencomputers|core   | 1.7.5.192         | minecraft.jar                                          | None      |
	| LCHIJA | architecturecraft    | @VERSION@         | architecturecraft-1.12-3.98 (1).jar                    | None      |
	| LCHIJA | mw                   | 0.4.6.2           | mw_2.0-0.4.6.2_mc1.12.2 (1).jar                        | None      |
	| LCHIJA | cqc                  | @MOD_VERSION@     | CQC-1.0.0 (1).jar                                      | None      |
	| LCHIJA | creativecore         | 1.10.0            | CreativeCore_v1.10.44_mc1.12.2.jar                     | None      |
	| LCHIJA | forgelin             | 1.8.4             | Forgelin-1.8.4.jar                                     | None      |
	| LCHIJA | furenikusroads       | 1.1.9             | Fureniku's+Roads-1.1.9 (1).jar                         | None      |
	| LCHIJA | hbm                  | hbm-1.4.0A-1.12.2 | hbm-1.4.1a (1).jar                                     | None      |
	| LCHIJA | igwmod               | 1.4.4-15          | IGW-Mod-1.12.2-1.4.4-15-universal (1).jar              | None      |
	| LCHIJA | trackapi             | 1.2               | TrackAPI-1.2 (1).jar                                   | None      |
	| LCHIJA | universalmodcore     | 1.0.1             | UniversalModCore-1.12.2-forge-1.0.1 (1).jar            | None      |
	| LCHIJA | immersiverailroading | 1.8.0-7e0f82      | ImmersiveRailroading-1.12.2-forge-1.8.0-7e0f82 (1).jar | None      |
	| LCHIJA | littleopener         | 1.0.1             | littleopener-1.0.1.jar                                 | None      |
	| LCHIJA | littletiles          | 1.5.0             | LittleTiles_v1.5.0-pre320_mc1.12.2.jar                 | None      |
	| LCHIJA | opencomputers        | 1.7.5.192         | OpenComputers-MC1.12.2-1.7.5.192 (2).jar               | None      |
	| LCHIJA | gvc                  | 1.2.0             | Voice+Chat+Reloaded-1.2.4.jar                          | None      |
	| LCHIJA | immersiveengineering | 0.12-98           | ImmersiveEngineering-0.12-98 (1).jar                   | None      |

	Loaded coremods (and transformers): 
LittlePatchingLoader (LittleTiles_v1.5.0-pre320_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CreativePatchingLoader (CreativeCore_v1.10.44_mc1.12.2.jar)
  
ForgelinPlugin (Forgelin-1.8.4.jar)
  
weaponlib (mw_2.0-0.4.6.2_mc1.12.2 (1).jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192 (2).jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14757 Compatibility Profile Context 20.11.2 27.20.14501.18003' Renderer: 'Radeon RX 580 Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Radeon RX 580 Series GL version 4.6.14757 Compatibility Profile Context 20.11.2 27.20.14501.18003, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 1400 Quad-Core Processor 
	
	
	If you are wondering, changing the rams allocated makes no difference, so that isn't an efficient method.

**Comment by Drillgon200** [comment]
Fixed.
