### ISSUE TITLE
Hello I am having an issue with the vault doors. Very bad issue. Tried disabling aptifine and other visual mods but still glitchy.

### ISSUE THREAD

**Issue by HaxerCoder** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#46]
![2021-01-25_19 09 10](https://user-images.githubusercontent.com/72237944/105795126-2567ba80-5f41-11eb-9be8-bc168fdfa2f5.png)
Very annoying issue cannot make a meme vault door.

**Comment by Drillgon200** [comment]
I'm not getting any problems like that, so it's likely another mod screwed up the gl state. What mods do you have in your pack?

**Comment by HaxerCoder** [comment]
Well I disabled all other addons but the problem persisted. I even used a different installation and it continued. Tried different forge versions, same problem. Even tried it on my linux installation because I thought maybe its a windows driver issue, but it still didnt fix anything. The only thing I think could be the problem is my graphics card, or rather lack of. This was on my intel NUC kit with an Intel IGP. So if you know anything about unsupported hardware, It would be appreciated!

**Comment by Drillgon200** [comment]
So it still happens with no other mods installed? Does it happen with both doors, or only one of them? I don't believe either of these doors do anything past OpenGL 1.1, other than maybe using the tessellator, but vanilla also uses that.

**Comment by HaxerCoder** [comment]
Hello, I managed to fix the problem by editing my windows driver settings to be in compatibility mode. I did however have to set my graphics to fast as well. But it works great now. Thank you for your time.

**Comment by Drillgon200** [comment]
Oh, neat. What a wacky issue, never seen that happen before.
