### ISSUE TITLE
HBM's Nuclear Tech Mod loaded a new chunk in dimension 0 (overworld) while populating chunk, causing cascading worldgen lag.

### ISSUE THREAD

**Issue by vesko128** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#47]
[latest.log](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/5926641/latest.log)

Have no idea what's causing it.

**Comment by Drillgon200** [comment]
I do, and I'm not fixing it.

**Comment by Drillgon200** [comment]
There's a forge option to turn the log off if you don't want to see it.
