### ISSUE TITLE
shredder not working as intended

### ISSUE THREAD

**Issue by james6858** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#49]
shredder is supposed to shred iron ore to iron powder or it works differently now

**Comment by UFFR** [comment]
The shredder is currently severely bugged with most generated recipes 
not working and returning scrap, it is a known bug. Non-generated 
recipes and/or ones visible with NEI/JEI should still work however.

-- 
UFFR

**Comment by Drillgon200** [comment]
Fixed in dev.
