### ISSUE TITLE
Cannot extract power from HE to RF Converter

### ISSUE THREAD

**Issue by Tech0verlord** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#5]
Just a quick and dirty reference to the original issue until any fixes are merged into the repo.

HbmMods/Hbm-s-Nuclear-Tech-GIT#76

Managed to get a workspace up and running, unfortunately, don't have much coding or modding experience, been just playing with the files.

**Comment by Drillgon200** [comment]
![2020-07-22_12 08 25](https://user-images.githubusercontent.com/50186362/88217907-1d3a6580-cc14-11ea-9701-16db0a703ab8.png)
I don't know, this is working perfectly fine for me.

**Comment by Drillgon200** [comment]
Well, you can use thermal's energy pipes or stick a mekanism cube next to it apparently. I'll try to get it to work with ender io pipes though.

**Comment by Tech0verlord** [comment]
Just a little heads up, it seems Xnet can't interact with  the converter either, wont extract power to the controller, and it won't transfer to other devices connected to via Xnet cables.

**Comment by Drillgon200** [comment]
Pretty sure this was fixed, reopen if not.
