### ISSUE TITLE
Oil Refinery mising textures

### ISSUE THREAD

**Issue by SzerGRA** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#50]
I have no textures in oil refinery i use version 1.4.1a from 
https://www.curseforge.com/minecraft/mc-mods/hbms-nuclear-tech-mod-reloaded

**Comment by SzerGRA** [comment]
![Minecraft 1 12 2 15 02 2021 15_12_22](https://user-images.githubusercontent.com/79095633/107957414-e0173580-6fa0-11eb-942e-28b6553c3962.png)

**Comment by TheForge129** [comment]
Drillgon has addressed this issue already, I believe he is going to fix it
in the next release

**Comment by SzerGRA** [comment]
K

**Comment by abel1502** [comment]
Still a problem, btw
