### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by toddw183** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#52]
Is there a way to keep item pipes (like those in Enderio and Thermal) from putting items in the export slot of machines like the Centrifuge.

**Comment by Drillgon200** [comment]
I don't know. I guess you can if they have a slot config. They don't use the newer machine base class that solves that.

**Comment by Drillgon200** [comment]
Oh yeah, you can use integrated dynamics.

**Comment by Drillgon200** [comment]
Centrifuge fixed. If you find more machines like that, list them here, reopen, and I'll fix those, too.
