### ISSUE TITLE
Upload to Curseforge

### ISSUE THREAD

**Issue by hofq** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#54]
Hey There,
I am at setting up an Modpack, but i can't Use this Mod, because the Latest version of the 1.12 got Removed From the Page of This Guy:
https://www.curseforge.com/minecraft/mc-mods/hbm-nuclear-tech-mod-1-12-2

It would be nice, if you could allow him to use it, or upload the File yourself. I would use the Github Version for the Modpack, but Curseforge Dont allow any  Modpack with an File, that was previously deleted from Curseforge.

I hope its understandable, and have a nice day

**Comment by Drillgon200** [comment]
Someone already did that.
https://www.curseforge.com/minecraft/mc-mods/hbms-nuclear-tech-mod-reloaded

**Comment by hofq** [comment]
> Someone already did that.
> https://www.curseforge.com/minecraft/mc-mods/hbms-nuclear-tech-mod-reloaded

Oh okay, It was Buggy but seems okay. Thanks for the Response :)
