### ISSUE TITLE
Conflict with mekanism?

### ISSUE THREAD

**Issue by mlodyskid** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#59]
i got a crash when loading the game with mekanism
when i delete HBM, error gone

Here is crash log:
https://pastebin.pl/view/11ea2f60

**Comment by Drillgon200** [comment]
Are you sure it's mekanism? Have you tested this mod on its own without it? Try updating your forge.

**Comment by mlodyskid** [comment]
but the problem is i want to play with HBM and mekanism. its because i played mekanism since i remember and i cant imagine "technical" modpack without it

**Comment by mlodyskid** [comment]
i delete mekanism and its working but as i wrote before, i really want to play with it

**Comment by Drillgon200** [comment]
I just wanted to know if it was actually a conflict with mekanism or just the forge version. Did you try updating forge just in case?

**Comment by mlodyskid** [comment]
yes i got the newest versino of forge

**Comment by Drillgon200** [comment]
Post a new crash report with the latest version of forge.

**Comment by mlodyskid** [comment]
okay, you right i downloaded the newest not even recommended forge and its working.

**Comment by Drillgon200** [comment]
Cool.
