### ISSUE TITLE
nevermind, got another: Automation is impossible

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#6]
Hoppers pull everything out of anything with an inventory. For example, cargo landing pads pull out the id chip, centrifuges have the stuff they're centrifuging pulled out, etc
This works the other way too. for centrifuges, stuff in hoppers can be put into the result slot, and that's the same for pretty much everything else

basically, automation isnt possible, which is a pretty huge deal for a large technology mod

**Comment by Tech0verlord** [comment]
For the cargo pad, you can just put an empty chest in front of the black dots on the center of each side. It will automatically output the contents of the inventory to the chest, without pulling out the ID Chip. From there you can add a hopper or whatever to the chest for automation. 

Haven't messed with the centrifuge yet, but it'd be safe to assume it would behave similarly; I know the assembly machine behaves the same way, with an input chest and output chest, it will automatically pull and push appropriate items in and out.

**Comment by TheForge129** [comment]
ah... should've known... would've saved a lot of time and hassle

**Comment by Drillgon200** [comment]
Hopper integration is a pain to deal with in 1.12.2 with their capability system. I made an abstraction for this for the machine base, but most of the machines don't use that.
