### ISSUE TITLE
Steam turbine stops moving water out after running for a while

### ISSUE THREAD

**Issue by churipputori** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#62]
I have made a water loop using a boiler and a steam turbine, and I noticed that after a while of running on its own, it will randomly stop pumping water out of the steam turbine, instead filling up the output buffer until it either depletes the boiler's water reserves or the buffer gets completely full, causing the system to stop entirely. Merely adding a pipe and tagging it, even one that leads to nothing, seems to cause the turbine to update, causing the entire output buffer to dump back into the boiler. Even if both the output buffer of the turbine and the input buffer of the boiler are partially filled, the turbine will just start accumulating water seemingly at random. This only seems to happen with steam to water process, dense steams seem to work just fine.
A similar issue seems to happen with the boiler itself. I'm not sure if they're related, but here's a video demonstrating it.
https://youtu.be/1AVEX5jh7h8

By the way, just as a general question, in a system that constantly pumps water in, what do I do with all the waste water, other than connect it to a bunch of tanks?

Mod version is 1.4.0a-1.12.2, Forge version is 14.23.5.2854

**Comment by Drillgon200** [comment]
I guess you could pipe it into a fluid trashcan like the one from extra utilities.

**Comment by Drillgon200** [comment]
Fixed I think (now I just have to hope it doesn't break something else I didn't see). Also noticed that the boilers were arbitrarily capped at 2 buckets per second, which I removed.
