### ISSUE TITLE
Issues with Hoppers Extracting from inputs

### ISSUE THREAD

**Issue by garciainke** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#63]
When using the hopper on any of the furnaces with single outs (blast furnace, electric furnace, etc.) to pull outputs, the hopper pulls items from the inputs

**Comment by Drillgon200** [comment]
Yeah, those should probably be moved to that machine base class.

**Comment by Drillgon200** [comment]
The blast furnace and electric furnace have been fixed, reopen if you find any more machines with this issue.
