### ISSUE TITLE
level.dat bug or idk 

### ISSUE THREAD

**Issue by pepetoster** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#64]
forge mod loader detected that the backup level.dat is being used, on latest version i have this problem, on 1.3.5 version all work ok. If i press yes button, i see this ( screenshot).
![2021-03-18_18 37 51](https://user-images.githubusercontent.com/81186079/112044942-576d5580-8b5b-11eb-8110-1f848fd9f5f6.png)
 I've been trying to solve this problem for 3 days, maybe someone knows the solution here?

**Comment by Drillgon200** [comment]
Looks like some sort of world corruption. I don't know what's causing it or how to fix it and have never run into it myself. Maybe a log would help, but I doubt it.

**Comment by Drillgon200** [comment]
Eh, no idea how I'm supposed to fix this one. Reopen if you get that log and it contains something useful.
