### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Joey-Destroyah** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#67]
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to com.hbm.items.weapon.ItemGunBase
Exit Code: -1
hbm-1.4.1a.jar is the only file in the mods folder.
Here is the crash report:
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 4/1/21 7:35 PM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to com.hbm.items.weapon.ItemGunBase
	at com.hbm.items.weapon.ItemGunBase.getBeltType(ItemGunBase.java:438)
	at com.hbm.items.weapon.ItemGunBase.renderHUD(ItemGunBase.java:652)
	at com.hbm.main.ModEventHandlerClient.onOverlayRender(ModEventHandlerClient.java:1144)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_49_ModEventHandlerClient_onOverlayRender_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:338)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:142)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.hbm.items.weapon.ItemGunBase.getBeltType(ItemGunBase.java:438)
	at com.hbm.items.weapon.ItemGunBase.renderHUD(ItemGunBase.java:652)
	at com.hbm.main.ModEventHandlerClient.onOverlayRender(ModEventHandlerClient.java:1144)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_49_ModEventHandlerClient_onOverlayRender_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:338)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:142)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Joseph_da_IT_Guy'/100090993, l='MpServer', x=192.72, y=74.00, z=301.22]]
	Chunk stats: MultiplayerChunkCache: 431, 431
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (208,64,252), Chunk: (at 0,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 45488 game time, 7568 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 95 total; [EntityWolf['Wolf'/100090867, l='MpServer', x=231.51, y=78.00, z=242.64], EntityWolf['Wolf'/100090879, l='MpServer', x=245.50, y=81.00, z=259.50], EntityWolf['Wolf'/100090878, l='MpServer', x=250.50, y=82.00, z=240.50], EntityWolf['Wolf'/100090877, l='MpServer', x=250.50, y=82.00, z=242.50], EntityWolf['Wolf'/100090876, l='MpServer', x=262.24, y=83.00, z=243.31], EntityWolf['Wolf'/100090875, l='MpServer', x=252.50, y=82.00, z=239.50], EntitySquid['Squid'/100099047, l='MpServer', x=169.02, y=59.06, z=327.97], EntityWitch['Witch'/100106721, l='MpServer', x=216.50, y=75.00, z=226.50], EntityZombie['Zombie'/100106720, l='MpServer', x=214.50, y=75.00, z=225.50], EntityWolf['Wolf'/100090856, l='MpServer', x=198.23, y=73.00, z=222.53], EntityZombie['Zombie'/100106706, l='MpServer', x=260.50, y=79.00, z=271.50], EntitySkeleton['Skeleton'/100106693, l='MpServer', x=153.50, y=65.00, z=225.50], EntityXPOrb['Experience Orb'/100098499, l='MpServer', x=155.25, y=41.00, z=342.55], EntityBat['Bat'/100106677, l='MpServer', x=264.37, y=18.10, z=378.88], EntitySkeleton['Skeleton'/100106684, l='MpServer', x=124.50, y=67.00, z=306.50], EntitySpider['Spider'/100106150, l='MpServer', x=190.30, y=24.00, z=372.70], EntityItem['item.item.dyePowder.black'/100098474, l='MpServer', x=156.38, y=40.00, z=341.14], EntityZombie['Zombie'/100106641, l='MpServer', x=259.17, y=72.00, z=294.65], EntityCreeper['Creeper'/100106654, l='MpServer', x=177.50, y=72.00, z=240.50], EntityXPOrb['Experience Orb'/100098439, l='MpServer', x=153.53, y=37.00, z=317.56], EntityZombie['Zombie'/100106628, l='MpServer', x=243.50, y=25.00, z=343.50], EntityZombie['Zombie'/100106627, l='MpServer', x=239.50, y=25.00, z=343.50], EntityZombie['Zombie'/100106636, l='MpServer', x=271.50, y=13.00, z=315.50], EntityCreeper['Creeper'/100107127, l='MpServer', x=140.50, y=15.00, z=265.50], EntityCreeper['Creeper'/100107126, l='MpServer', x=136.50, y=15.00, z=266.50], EntitySkeleton['Skeleton'/100107123, l='MpServer', x=140.50, y=15.00, z=266.50], EntityCreeper['Creeper'/100099442, l='MpServer', x=272.21, y=23.00, z=352.30], EntitySkeleton['Skeleton'/100106623, l='MpServer', x=185.50, y=45.00, z=224.50], EntityItem['item.item.dyePowder.black'/100098429, l='MpServer', x=158.43, y=37.00, z=318.37], EntityItem['item.item.egg'/100107131, l='MpServer', x=200.13, y=73.00, z=249.13], EntityBat['Bat'/100107110, l='MpServer', x=124.29, y=38.60, z=290.60], EntityBat['Bat'/100107109, l='MpServer', x=123.09, y=38.06, z=295.26], EntityBat['Bat'/100107107, l='MpServer', x=123.76, y=37.11, z=295.00], EntityBat['Bat'/100107106, l='MpServer', x=117.22, y=37.10, z=299.55], EntityXPOrb['Experience Orb'/100098415, l='MpServer', x=161.25, y=62.00, z=287.25], EntityBat['Bat'/100107112, l='MpServer', x=142.25, y=17.00, z=268.25], EntitySkeleton['Skeleton'/100107093, l='MpServer', x=272.50, y=80.00, z=265.50], EntitySquid['Squid'/100104016, l='MpServer', x=186.49, y=54.45, z=325.09], EntitySkeleton['Skeleton'/100106591, l='MpServer', x=254.50, y=11.00, z=330.50], EntitySkeleton['Skeleton'/100106590, l='MpServer', x=255.50, y=11.00, z=330.50], EntitySkeleton['Skeleton'/100107098, l='MpServer', x=132.50, y=68.00, z=267.50], EntityZombie['Zombie'/100107097, l='MpServer', x=137.50, y=68.00, z=268.50], EntityBat['Bat'/100107086, l='MpServer', x=139.49, y=43.91, z=242.43], EntityBat['Bat'/100107085, l='MpServer', x=135.58, y=41.64, z=247.75], EntitySquid['Squid'/100104008, l='MpServer', x=193.05, y=57.91, z=343.53], EntitySquid['Squid'/100103990, l='MpServer', x=203.78, y=47.41, z=328.91], EntityBat['Bat'/100101938, l='MpServer', x=114.75, y=23.10, z=266.25], EntityZombie['Zombie'/100106559, l='MpServer', x=264.50, y=16.00, z=353.50], EntityEnderman['Enderman'/100106557, l='MpServer', x=215.41, y=75.00, z=225.51], EntityCreeper['Creeper'/100102460, l='MpServer', x=253.50, y=12.00, z=290.50], EntitySquid['Squid'/100103996, l='MpServer', x=224.04, y=53.98, z=329.77], EntitySkeleton['Skeleton'/100106556, l='MpServer', x=153.50, y=46.00, z=231.50], EntitySquid['Squid'/100103993, l='MpServer', x=197.60, y=45.95, z=330.03], EntityCreeper['Creeper'/100107046, l='MpServer', x=224.50, y=18.00, z=347.50], EntityPlayerSP['Joseph_da_IT_Guy'/100090993, l='MpServer', x=192.72, y=74.00, z=301.22], EntityBat['Bat'/100107043, l='MpServer', x=141.25, y=61.10, z=222.45], EntitySquid['Squid'/100103976, l='MpServer', x=207.03, y=62.00, z=354.88], EntityZombie['Zombie'/100102416, l='MpServer', x=239.50, y=23.00, z=335.50], EntityItem['item.item.dyePowder.black'/100099853, l='MpServer', x=221.72, y=48.00, z=342.93], EntityItem['item.item.dyePowder.black'/100099852, l='MpServer', x=218.52, y=45.00, z=347.79], EntityItem['item.item.dyePowder.black'/100099851, l='MpServer', x=213.72, y=38.00, z=351.51], EntityItem['item.item.dyePowder.black'/100099850, l='MpServer', x=220.17, y=48.00, z=337.55], EntityWitch['Witch'/100106996, l='MpServer', x=132.50, y=27.00, z=326.50], EntitySquid['Squid'/100103931, l='MpServer', x=179.17, y=54.04, z=349.71], EntitySkeleton['Skeleton'/100104421, l='MpServer', x=239.53, y=52.00, z=311.09], EntityCreeper['Creeper'/100106981, l='MpServer', x=177.23, y=73.00, z=246.51], EntityBat['Bat'/100106463, l='MpServer', x=139.64, y=41.50, z=234.40], EntityDuck['Duck'/100096734, l='MpServer', x=200.39, y=73.00, z=249.87], EntitySquid['Squid'/100103900, l='MpServer', x=170.57, y=61.73, z=285.06], EntitySquid['Squid'/100103898, l='MpServer', x=182.40, y=62.00, z=272.80], EntityZombie['Zombie'/100106458, l='MpServer', x=112.75, y=20.00, z=254.53], EntitySkeleton['Skeleton'/100106447, l='MpServer', x=209.50, y=16.00, z=236.50], EntityPlayerSP['Joseph_da_IT_Guy'/100090993, l='MpServer', x=60.67, y=-97.21, z=511.33], EntityZombie['Zombie'/100106931, l='MpServer', x=220.50, y=16.00, z=380.50], EntityZombie['Zombie'/100106899, l='MpServer', x=233.50, y=77.00, z=230.50], EntitySpider['Spider'/100106895, l='MpServer', x=180.50, y=73.00, z=251.50], EntityCreeper['Creeper'/100103822, l='MpServer', x=210.50, y=21.00, z=224.50], EntitySquid['Squid'/100096116, l='MpServer', x=9.50, y=59.00, z=477.50], EntityXPOrb['Experience Orb'/100098163, l='MpServer', x=159.12, y=35.00, z=326.30], EntityCreeper['Creeper'/100101218, l='MpServer', x=265.50, y=18.00, z=356.50], EntitySkeleton['Skeleton'/100106850, l='MpServer', x=195.50, y=64.00, z=277.21], EntityXPOrb['Experience Orb'/100098135, l='MpServer', x=168.70, y=37.00, z=325.29], EntityXPOrb['Experience Orb'/100098133, l='MpServer', x=152.31, y=46.00, z=345.78], EntityItem['item.item.dyePowder.black'/100098131, l='MpServer', x=158.69, y=38.00, z=317.27], EntitySpider['Spider'/100106844, l='MpServer', x=244.50, y=18.00, z=355.50], EntityXPOrb['Experience Orb'/100098136, l='MpServer', x=164.72, y=38.00, z=318.47], EntityItem['item.item.dyePowder.black'/100098117, l='MpServer', x=152.19, y=47.00, z=347.50], EntityItem['item.item.dyePowder.black'/100098127, l='MpServer', x=163.82, y=35.00, z=322.05], EntityCreeper['Creeper'/100106831, l='MpServer', x=212.50, y=21.00, z=357.50], EntitySpider['Spider'/100106806, l='MpServer', x=269.50, y=12.00, z=374.50], EntitySpider['Spider'/100105278, l='MpServer', x=235.50, y=14.00, z=360.50], EntityBat['Bat'/100106784, l='MpServer', x=232.54, y=21.44, z=350.47], EntityWolf['Wolf'/100090881, l='MpServer', x=245.57, y=78.00, z=266.07], EntityWolf['Wolf'/100090880, l='MpServer', x=241.49, y=80.00, z=253.75], EntitySkeleton['Skeleton'/100106763, l='MpServer', x=215.46, y=69.00, z=288.26]]
	Retry entities: 90 total; [EntitySquid['Squid'/100096116, l='MpServer', x=9.50, y=59.00, z=477.50], EntitySquid['Squid'/100096115, l='MpServer', x=8.50, y=59.00, z=478.50], EntitySquid['Squid'/100096114, l='MpServer', x=5.50, y=59.00, z=482.50], EntitySquid['Squid'/100096113, l='MpServer', x=8.50, y=59.00, z=482.50], EntitySquid['Squid'/100095847, l='MpServer', x=3.50, y=52.00, z=454.50], EntitySquid['Squid'/100095845, l='MpServer', x=-0.50, y=52.00, z=455.50], EntitySquid['Squid'/100095844, l='MpServer', x=-0.50, y=52.00, z=456.50], EntitySquid['Squid'/100095843, l='MpServer', x=15.50, y=52.00, z=484.50], EntityVillager['Villager'/100091107, l='MpServer', x=75.65, y=72.00, z=544.50], EntityBat['Bat'/100096098, l='MpServer', x=24.50, y=25.10, z=469.50], EntitySquid['Squid'/100095842, l='MpServer', x=17.50, y=52.00, z=487.50], EntityVillager['Villager'/100091106, l='MpServer', x=54.71, y=68.00, z=557.61], EntityBat['Bat'/100096097, l='MpServer', x=25.50, y=25.10, z=473.50], EntitySquid['Squid'/100095841, l='MpServer', x=22.50, y=52.00, z=487.50], EntityVillager['Villager'/100091105, l='MpServer', x=55.65, y=68.00, z=560.51], EntitySquid['Squid'/100095840, l='MpServer', x=26.50, y=52.00, z=486.50], EntityVillager['Villager'/100091104, l='MpServer', x=48.49, y=67.00, z=571.97], EntitySpider['Spider'/100095968, l='MpServer', x=80.50, y=32.00, z=558.50], EntityCreeper['Creeper'/100093548, l='MpServer', x=26.50, y=22.00, z=480.50], EntityBat['Bat'/100096108, l='MpServer', x=42.50, y=48.10, z=580.50], EntityCreeper['Creeper'/100093547, l='MpServer', x=28.50, y=22.00, z=480.50], EntityBat['Bat'/100096107, l='MpServer', x=43.50, y=48.10, z=582.50], EntitySkeleton['Skeleton'/100095976, l='MpServer', x=35.50, y=64.00, z=545.50], EntitySquid['Squid'/100095831, l='MpServer', x=15.50, y=60.00, z=477.50], EntityCreeper['Creeper'/100096084, l='MpServer', x=67.50, y=71.00, z=455.50], EntityCreeper['Creeper'/100096082, l='MpServer', x=-1.50, y=36.00, z=435.50], EntitySpider['Spider'/100095967, l='MpServer', x=83.50, y=32.00, z=554.50], EntityVillager['Villager'/100091103, l='MpServer', x=83.33, y=71.00, z=552.80], EntityVillager['Villager'/100091102, l='MpServer', x=65.55, y=68.00, z=561.34], EntityCreeper['Creeper'/100095966, l='MpServer', x=89.50, y=29.00, z=443.50], EntityVillager['Villager'/100091101, l='MpServer', x=65.01, y=68.00, z=562.16], EntityVillager['Villager'/100091100, l='MpServer', x=35.30, y=64.00, z=544.42], EntityVillager['Villager'/100091099, l='MpServer', x=66.55, y=72.00, z=543.66], EntitySquid['Squid'/100095834, l='MpServer', x=7.50, y=60.00, z=475.50], EntitySquid['Squid'/100095450, l='MpServer', x=27.50, y=55.00, z=522.50], EntityVillager['Villager'/100091098, l='MpServer', x=58.30, y=70.00, z=544.24], EntitySquid['Squid'/100095833, l='MpServer', x=11.50, y=60.00, z=476.50], EntitySquid['Squid'/100095449, l='MpServer', x=26.50, y=55.00, z=530.50], EntityVillager['Villager'/100091097, l='MpServer', x=62.27, y=72.00, z=544.50], EntitySquid['Squid'/100095832, l='MpServer', x=10.50, y=60.00, z=479.50], EntityVillager['Villager'/100091096, l='MpServer', x=58.70, y=69.00, z=556.49], EntitySquid['Squid'/100095815, l='MpServer', x=123.50, y=56.00, z=505.50], EntitySquid['Squid'/100095684, l='MpServer', x=14.50, y=58.00, z=486.50], EntitySquid['Squid'/100095683, l='MpServer', x=12.50, y=58.00, z=489.50], EntitySquid['Squid'/100095682, l='MpServer', x=11.50, y=58.00, z=478.50], EntitySquid['Squid'/100095426, l='MpServer', x=38.50, y=61.00, z=492.50], EntitySquid['Squid'/100095681, l='MpServer', x=12.50, y=58.00, z=481.50], EntitySquid['Squid'/100095425, l='MpServer', x=40.50, y=61.00, z=495.50], EntitySquid['Squid'/100095424, l='MpServer', x=37.50, y=61.00, z=499.50], EntityVillager['Villager'/100091072, l='MpServer', x=49.46, y=66.00, z=530.30], EntitySquid['Squid'/100095822, l='MpServer', x=40.50, y=60.00, z=506.50], EntitySquid['Squid'/100095821, l='MpServer', x=46.50, y=60.00, z=508.50], EntitySquid['Squid'/100095820, l='MpServer', x=45.50, y=60.00, z=507.50], EntitySquid['Squid'/100095819, l='MpServer', x=39.50, y=60.00, z=505.50], EntitySquid['Squid'/100095818, l='MpServer', x=124.50, y=56.00, z=500.50], EntitySquid['Squid'/100095817, l='MpServer', x=121.50, y=56.00, z=501.50], EntitySquid['Squid'/100095816, l='MpServer', x=123.50, y=56.00, z=509.50], EntitySquid['Squid'/100096176, l='MpServer', x=124.50, y=59.00, z=526.50], EntitySquid['Squid'/100095423, l='MpServer', x=34.50, y=61.00, z=500.50], EntityVillager['Villager'/100091071, l='MpServer', x=56.97, y=71.00, z=528.50], EntityVillager['Villager'/100091069, l='MpServer', x=28.56, y=63.94, z=544.61], EntitySquid['Squid'/100095397, l='MpServer', x=109.50, y=62.00, z=516.50], EntitySquid['Squid'/100095396, l='MpServer', x=119.50, y=62.00, z=523.50], EntitySquid['Squid'/100096163, l='MpServer', x=31.50, y=61.00, z=526.50], EntitySquid['Squid'/100095395, l='MpServer', x=114.50, y=62.00, z=521.50], EntitySquid['Squid'/100096162, l='MpServer', x=32.50, y=61.00, z=524.50], EntitySquid['Squid'/100095394, l='MpServer', x=112.50, y=62.00, z=520.50], EntitySquid['Squid'/100096161, l='MpServer', x=28.50, y=61.00, z=526.50], EntitySquid['Squid'/100096160, l='MpServer', x=29.50, y=61.00, z=527.50], EntitySquid['Squid'/100095532, l='MpServer', x=31.50, y=59.00, z=511.50], EntitySquid['Squid'/100095531, l='MpServer', x=33.50, y=59.00, z=513.50], EntitySquid['Squid'/100095530, l='MpServer', x=34.50, y=59.00, z=511.50], EntitySquid['Squid'/100095529, l='MpServer', x=34.50, y=59.00, z=512.50], EntityVillager['Villager'/100091048, l='MpServer', x=49.54, y=64.00, z=516.30], EntityBat['Bat'/100095767, l='MpServer', x=76.50, y=39.10, z=444.50], EntityBat['Bat'/100095893, l='MpServer', x=96.50, y=26.10, z=526.50], EntityBat['Bat'/100095635, l='MpServer', x=-10.50, y=30.10, z=449.50], EntityCreeper['Creeper'/100095378, l='MpServer', x=47.50, y=67.00, z=541.50], EntityBat['Bat'/100095762, l='MpServer', x=127.50, y=14.10, z=453.50], EntitySquid['Squid'/100095901, l='MpServer', x=6.50, y=56.00, z=465.50], EntitySquid['Squid'/100095900, l='MpServer', x=6.50, y=56.00, z=463.50], EntitySquid['Squid'/100095899, l='MpServer', x=6.50, y=56.00, z=460.50], EntitySquid['Squid'/100095898, l='MpServer', x=5.50, y=56.00, z=457.50], EntitySquid['Squid'/100095620, l='MpServer', x=58.50, y=61.00, z=482.50], EntitySquid['Squid'/100095619, l='MpServer', x=58.50, y=61.00, z=480.50], EntitySquid['Squid'/100095617, l='MpServer', x=58.50, y=61.00, z=477.50], EntitySquid['Squid'/100096129, l='MpServer', x=82.50, y=59.00, z=447.50], EntitySquid['Squid'/100095616, l='MpServer', x=59.50, y=61.00, z=477.50], EntityCreeper['Creeper'/100095885, l='MpServer', x=86.50, y=33.00, z=563.50], EntitySquid['Squid'/100096138, l='MpServer', x=102.50, y=62.00, z=516.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 463095232 bytes (441 MB) / 1610612736 bytes (1536 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version           | Source                        | Signature |
	|:------ |:--------- |:----------------- |:----------------------------- |:--------- |
	| LCHIJA | minecraft | 1.12.2            | minecraft.jar                 | None      |
	| LCHIJA | mcp       | 9.42              | minecraft.jar                 | None      |
	| LCHIJA | FML       | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | forge     | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | hbm       | hbm-1.4.0A-1.12.2 | hbm-1.4.1a.jar                | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
Hopefully you can help.

**Comment by Drillgon200** [comment]
Were you using a gun in your offhand?

**Comment by Joey-Destroyah** [comment]
I think I was.

**Comment by Drillgon200** [comment]
Alright, I think it's fixed then. I was getting the gun from the main hand no matter what rather than using the hand I passed in.

**Comment by Drillgon200** [comment]
Also wow that was a quick reply.
