### ISSUE TITLE
Radiation absorvers bug?

### ISSUE THREAD

**Issue by jose-manuel-silva** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#68]
I have a server with hbm, and a friend of mine opened a glitch, and it dropped a nuclear bomb, destroying the entire spawn. I'm trying to remove the radiation with radiation absorvers, but they can't maintant 0 rad/s, I've even tried to place multiple absorvers, but radiation keeps oscilating like in the image below.

![penheta](https://user-images.githubusercontent.com/52240775/113493078-5382f100-94d4-11eb-8f25-0ebbe96aaebe.png)

**Comment by Drillgon200** [comment]
That's not necessarily a bug. They only remove radiation every half a second, radiation has plenty of time to accumulate over that time. If you want the radiation gone, remove the radiation source.
