### ISSUE TITLE
Only one now... I was having fun with the bundle packs you monster.

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#7]
~~-Missile silos dont work~~
~~-Radial performance engines wont take a fluid identifier even though theres a slot for it~~
~~-Radial performance engines won't actually output their power through a cable~~
~~-Enchantment-based tool abilities don't work~~
~~-Mercury bottles dont work (i. e. they cant be put into a tank)~~

And another one: Basically everything concerning energy storage and batteries is broken, i cant even describe this... the textures are broken, and there's even energy duplication

i'm sorry if all these issues are kinda annoying you, i just dont want a broken 1.12.2 release tbh

**Comment by Drillgon200** [comment]
These don't annoy me, I very much love bug reports. There probably shouldn't be a slot for the fluid identifier in the performance engine. They actually do output power, but only down. I've already fixed the silk and fortune abilities, the mercury bottles, and the silo hatch.

**Comment by TheForge129** [comment]
But really though, at what point does it turn from playing to unpaid playtesting?

**Comment by TheForge129** [comment]
@Drillgon200 Do you get notified of edits?

**Comment by Drillgon200** [comment]
No, and I'm decently sure that I already fixed the battery textures and at least one energy duplication issue.
