### ISSUE TITLE
Tank problem

### ISSUE THREAD

**Issue by abel1502** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#70]
Fluid tank doesn't fill buckets with crude oil. It consumes the liquid from the tank, but the bucket remains empty and in the top slot

**Comment by TheForge129** [comment]
crude oil buckets don't exist

**Comment by Drillgon200** [comment]
I'm pretty sure it's not supposed to fill buckets.

**Comment by abel1502** [comment]
But then I'd expect its contents not to be drained neither. (Also in this case it would be nice if it didn't accept buckets at all, but that's optional)

**Comment by Drillgon200** [comment]
I guess I must have fixed it already because I can't replicate it in dev.

**Comment by abel1502** [comment]
It's still broken in the latest update. To reproduce:
 - Place a filled bucket in a tank's deposit slot. (I tested on water this time)
 - It will get emptied, the fluid will be transfered to the tank and the bucket will move to the bottom slot
 - Move the same bucket to the extraction slot
 - The tank will become empty again, but the bucket will stay in the top slot and remain empty

**Comment by Drillgon200** [comment]
Ok now it's fixed.
