### ISSUE TITLE
Problem with mode-switching tools

### ISSUE THREAD

**Issue by abel1502** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#71]
When the player holds something placeable in the offhand and a mode-switching tool in the main one, right-clicking triggers both.

**Comment by Drillgon200** [comment]
Could you explain what a mode switching tool is?

**Comment by TheForge129** [comment]
i'll do it for him
for example, a desh pickaxe with veinminer, aoe, etc

**Comment by abel1502** [comment]
Yes, exactly what @TheForge129  said. In my case, it was an impact drill (and in the off hand, I had torches). (Sorry for not providing enough details initially, I was kinda busy at the time of writing the issue)
