### ISSUE TITLE
Crash on loading/creating world 

### ISSUE THREAD

**Issue by Aperagit** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#72]
Crashing when I load into the world haven't had this problem until I upgraded from hbm-1.3.7.1a to hbm-1.4.1a
worked yesterday and now I can't load into my world nor create a new world without it crashing

Any help would be appreciated
[Crash.txt](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/6394552/Crash.txt)

**Comment by Drillgon200** [comment]
This one's been reported before, and I have no idea how it happens. Haven't been able to recreate it.

**Comment by Drillgon200** [comment]
Alright, I looked at some other mod that had the same issue, and did a thing that may or may not have fixed it. I'll close this for now, reopen if it still happens in the next release.

**Comment by Aperagit** [comment]
Alright
