### ISSUE TITLE
(1.12.2)Guns not firing 

### ISSUE THREAD

**Issue by Goosegg23** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#76]
At first, when I installed the mod, guns worked fine. however, after using the minigun for a little while, no other gun would fire. they would reload and aim but not shoot. I then made a new world and they didn't work there, either. turrets and bombs still work, as does basically everything else as far as I know. right-click weapons such as the Immolator work fine too.

**Comment by Drillgon200** [comment]
I believe I have fixed that, reopen if it is not fixed in the next update.

**Comment by Goosegg23** [comment]
Actually, it is now fixed, all I had to do was completely restart Minecraft.

**Comment by Drillgon200** [comment]
Yeah, I know, but I still needed to fix the bug that requires you to restart minecraft.
