### ISSUE TITLE
Big black triangle 1.4.3

### ISSUE THREAD

**Issue by HarleenUSA** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#80]
There is a one face big black triangle over my character
![2021-05-15_14 49 26](https://user-images.githubusercontent.com/83119904/118361679-d051c200-b58c-11eb-9fc6-753b601d899e.png)

**Comment by Drillgon200** [comment]
Could you upload a log? Also, are you on mac?

**Comment by HarleenUSA** [comment]
Yes I'm on a mid 2010 mac.

Here's a log
[latest.log](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/6488375/latest.log)

**Comment by Drillgon200** [comment]
Yeah, I was afraid of that. For some reason, Apple decided to stop supporting OpenGL, which means almost none of my shaders will work correctly on OSX. In the next bug fix release, I've included an option to disable all shaders which you can use.
