### ISSUE TITLE
GL ERROR when using Optifine since version 1.4.3

### ISSUE THREAD

**Issue by Devnary** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#82]
Game spam logs with this : 
```
[18:45:08] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[18:45:08] [Client thread/ERROR] [minecraft/Minecraft]: @ Post render
[18:45:08] [Client thread/ERROR] [minecraft/Minecraft]: 1286: Invalid framebuffer operation
[18:45:08] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[18:45:08] [Client thread/ERROR] [minecraft/Minecraft]: @ Post render
[18:45:08] [Client thread/ERROR] [minecraft/Minecraft]: 1286: Invalid framebuffer operation
[18:45:08] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[18:45:08] [Client thread/ERROR] [minecraft/Minecraft]: @ Post render
[18:45:08] [Client thread/ERROR] [minecraft/Minecraft]: 1286: Invalid framebuffer operation
```
More info : 
OS : Linux 5.15.2
GPU : AMD Radeon Vega 3
GL : OpenGL 3.1

These errors will happen only when Optifine is installed
Game window completely blank after loading any world or joining any server.

Sorry for the double issue x)

**Comment by Drillgon200** [comment]
Do you have fast render enabled? And to be perfectly clear, the screen is blank and the log messages happen only when optifine is present, right?

**Comment by Devnary** [comment]
Yes I use fast render, and fast math too
Because I don't care how ugly my game can be, just I don't want to play at 20fps x)

Yes you're right.

**Comment by Drillgon200** [comment]
Fast render isn't going to work. It disables the shader pipeline, and many of my visuals rely on shaders working. You can disable many of these effects in the config, but I need to go through it again and ensure that my disable code actually works.

**Comment by Drillgon200** [comment]
So, either disable fast render or disable the things that use shaders in the config, they're mutually exclusive.

**Comment by Devnary** [comment]
I will disable the fast render. It's the simplest choice

Thanks for the help 👍.

**Comment by Drillgon200** [comment]
I'll release a bug fix update soon which will allow you to easily disable all NTM shaders with one config option if you want to go that route.

**Comment by Goosegg23** [comment]
So, I have fast render disabled, but I have been experiencing something very wacky.
https://youtu.be/IvL2KEWEiig
https://youtu.be/gPSuc9LVMHc
It's the bottom one

**Comment by Drillgon200** [comment]
Fascinating. Are you sure it's caused by NTM?

**Comment by Goosegg23** [comment]
I know it is in some way caused by the new NTM and that it is probably conflicting woth another mod. I did not have this problem before. I removed optifine and I'll see if that helps. It does this whenever I move, so maybe disabling swaying will mitigate it.

**Comment by Goosegg23** [comment]
Ok so I did some testing and for some reason it only lets me move northwest and only when I press A. also, for some reason when I make one whole rotation, I fly faster? Weird, but I guess I'll have to wait until next release.

I don't know if this helps, but the Minecraft title background (the one that slowly pans around) is now moving super fast, just like my screen does when I move around.

**Comment by Drillgon200** [comment]
I have literally no clue how I'm supposed to fix this. I think I've seen a similar issue before with the arms spinning around, but that was a long time ago and I can't remember details about how it might have been fixed.

**Comment by Drillgon200** [comment]
Do you have better FPS installed? According to google that can cause this error.

**Comment by Goosegg23** [comment]
Yes, I do. I'll try to remove that to fix this later today. Thank you for all the help so far.

**Comment by Goosegg23** [comment]
Yep, worked. Changed BetterFps math to Riven's Math instead of random.

Thank you for the help!
