### ISSUE TITLE
1.4.3A Crash

### ISSUE THREAD

**Issue by FengXing945** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#83]
hbm1.4.3A Loading World Crash
[crash-2021-05-15_18.57.27-server.txt](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/6488085/crash-2021-05-15_18.57.27-server.txt)

**Comment by Drillgon200** [comment]
Fixed, I'll do a bug fix update soon.
