### ISSUE TITLE
New HBM cannot run with shaders evidently (1.4.3)

### ISSUE THREAD

**Issue by Goosegg23** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#86]
I checked this and the last version of HBM and the last version can run shaders just fine, but this one gets stuck on the shader "Dirt wall" meaning that the game itself runs fine (Can still get attacked by mobs, hear running water, etc.) but the video output is just the dirt screen you get for loading the whole time. I'm guessing this is due to the addition of custom shaders for this version in the newest update. Would there be any way to toggle these shaders or have them work with the visual shaders I would like to use?
![Base Profile Screenshot 2021 05 17 - 16 17 30 97](https://user-images.githubusercontent.com/83782796/118553121-e64ab880-b72d-11eb-9998-9f246abae282.png)
This image is what it looked like before 1.4.3. sorry for the bad screenshot, but you can see the shadows and such.

**Comment by Drillgon200** [comment]
Yes, this release is incompatible with shaders. If you look in the config file, you may see an option called something like enableShaders2. If you set that to false, it'll probably be fine.

**Comment by Drillgon200** [comment]
For future reference, it's always helpful to do a quick Ctrl F search in a mod's config file if you want a certain config option. There's a chance it already exists.

**Comment by Goosegg23** [comment]
Oh ok, thanks.
