### ISSUE TITLE
Visual Bug in 1.4.3a

### ISSUE THREAD

**Issue by Yuckiez** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#88]
So, i launch the game everything is fine but when i get in a world theres a black triangle of some sort obstructing my view. It seems to mess with my block placement and such. When i go into 3rd person mode and look at myself from the front, im able to see the full triangle.. 

I play on MacOS and hopefully you see this so you can fix it.

**Comment by Drillgon200** [comment]
Macs don't work with my shaders due to Apple deciding not to support open gl. Turn the enableShaders2 option to false in the config.

**Comment by Yuckiez** [comment]
> Macs don't work with my shaders due to Apple deciding not to support open gl. Turn the enableShaders2 option to false in the config.

How do i see config

**Comment by Yuckiez** [comment]
Nevermind

**Comment by Drillgon200** [comment]
So... did that fix it?

**Comment by Yuckiez** [comment]
> Macs don't work with my shaders due to Apple deciding not to support open gl. Turn the enableShaders2 option to false in the config.

Nope, it did not work

**Comment by Drillgon200** [comment]
Try redownloading the mod just in case you don't have the latest fix (I doubt it). Also send me the config so I can make sure you did that right.

**Comment by Yuckiez** [comment]
> Try redownloading the mod just in case you don't have the latest fix (I doubt it). Also send me the config so I can make sure you did that right.

for the config i found the "enableshaders2=true" and changed it to false, and im using the latest version of the mod, 1.4.3a

**Comment by Drillgon200** [comment]
Send a log.

**Comment by Yuckiez** [comment]
> Send a log.

Like what? the config or the log for when im playing with the issue?

**Comment by Drillgon200** [comment]
The log for when you're playing.

**Comment by Yuckiez** [comment]
i play with like 40 other mods are you sure

**Comment by Drillgon200** [comment]
Yes? Why would that change anything?

**Comment by Yuckiez** [comment]
you would have to go through 40x more stuff

**Comment by Yuckiez** [comment]
but sure

**Comment by Drillgon200** [comment]
Not really, I know what kind of thing I would be looking for.

**Comment by Yuckiez** [comment]
[2021-05-21-7.log.gz](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/6525559/2021-05-21-7.log.gz)

I believe this is it

**Comment by Drillgon200** [comment]
I don't think that's the right log. It's extremely short and I don't see any HBM log messages in it.

**Comment by Yuckiez** [comment]
nope, thats the log

**Comment by Drillgon200** [comment]
It literally doesn't even get past coremod loading, it's not the right log. Try loading the game again and uploading latest.log. If that still doesn't contain information, maybe one of the coremods you have installed is routing the log output somewhere else.

**Comment by Yuckiez** [comment]
[latest copy.log](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/files/6525602/latest.copy.log)


HEre

**Comment by Drillgon200** [comment]
Alright, shaders are still loading, so one of two things is happening. Either you didn't fully update NTM (1.4.3a does not necessarily mean the latest version, there are several releases with that version number, just with different amounts of bugs fixed), or you didn't turn enableShaders2 to false in the right file.

**Comment by Yuckiez** [comment]
> Alright, shaders are still loading, so one of two things is happening. Either you didn't fully update NTM (1.4.3a does not necessarily mean the latest version, there are several releases with that version number, just with different amounts of bugs fixed), or you didn't turn enableShaders2 to false in the right file.

i turned it off in the config "assemblerConfig" file and i download the latest file for HBM

**Comment by Devnary** [comment]
> > Alright, shaders are still loading, so one of two things is happening. Either you didn't fully update NTM (1.4.3a does not necessarily mean the latest version, there are several releases with that version number, just with different amounts of bugs fixed), or you didn't turn enableShaders2 to false in the right file.
> 
> i turned it off in the config "assemblerConfig" file and i download the latest file for HBM

`assemblerConfig` is not the config file. `enableShaders2` is located in `hbm.cfg`, line 61.

**Comment by Drillgon200** [comment]
Mug moment.
