### ISSUE TITLE
1.4.3a bug?

### ISSUE THREAD

**Issue by aj16789** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#89]
When I load into a world the screen flicker white, I'm on windows 10 Compatibility?

https://user-images.githubusercontent.com/58922612/118924562-25296b80-b8f2-11eb-80c7-efc454cf04c4.mp4

optifine appears to be the issue
when I removed optifine it stuck at 0%
I removed SecurityCraft that fixed it

**Comment by aj16789** [comment]
and the mod wont load

**Comment by Devnary** [comment]
Got the same issue (#82)
Go to the config file and turn `enableShaders2` to `false`

**Comment by Drillgon200** [comment]
What Devnary said. Shaders don't work with everyone's computer, so set them to false.
