### ISSUE TITLE
Can't remove recipes with crafttweaker

### ISSUE THREAD

**Issue by Unjustifiable** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#9]
Hi, so I am trying to remove crafting table recipes using craft tweaker for this mod so I can make harder recipes for my modpack but HBM seems to keep re-adding them after I remove them. Can you please fix this? Thank you.

**Comment by Drillgon200** [comment]
I can try. No idea why that might be happening. I guess it depends on when crafttweaker removes recipes.

**Comment by Unjustifiable** [comment]
Thank you for looking into it. It's just weird that this specific mod has issues with it's recipe's being removed via crafttweaker. It's the only mod that I've ran into with this problem.

**Comment by Drillgon200** [comment]
I register my recipes through code in postInit, most people register them with json files, so that's probably why.

**Comment by Shibva** [comment]
Remember that bug where the recipes are bug when being insereted I told you about in DMs?

This could be the same thinng or something that stems to that issue

**Comment by Drillgon200** [comment]
Fixed for I'm not sure how long.
