### ISSUE TITLE
A collection of questions (Low priority)

### ISSUE THREAD

**Issue by Goosegg23** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#90]
I had many questions and I thought I would Ask them at once instead of as separate issues.

1. If I were to put all the shaders stuff in the config as false and run minecraft with shaders, would the fps tank because things take longer to render or would the performance difference be negligible?
2. Do the new mini nukes travel way faster now? I don't remember them going that far before?
3. (LOW importance) are there any plans on making the other "mini nuke" explosions (Nuclear rocket, Fat mine, Etc.) modern as well?
4. (even LOWER importance) Would it be possible to add a timed function to the Custom Nuke, or create a new explosive that uses a timer like the balefire bomb does?
5. Are there any other places where you can put questions (Not issues, persay) other than this Issues tab?
6. What is Baby mode in the config?

Sorry for so many questions.

**Comment by Drillgon200** [comment]
Turning shaders to false simply removes all of NTM's shader effects. Some of the visuals will look considerably worse, but performance should actually improve quite a bit.
I'm pretty sure they were made faster so you didn't nuke yourself all the time.
Possibly, you'd have to talk to bob (the 1.7 dev) about that. 
Yes, it would be possible, but like you said, that would be a really low priority thing.
You can use discord for questions as well. Other than that, I don't know.
Baby mode makes the mod easier by doing things like making the schrabidium transmutor create ingots, allowing nuclear fallout to create schrabidium ore directly, turning coal directly into oil, and making schrabidium and starmetal stuff easier to craft.
