### ISSUE TITLE
Evil Radiation 1.4.4a

### ISSUE THREAD

**Issue by Shirhix** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#98]
The advanced radiation system is causing some chunk loading delay to the point where chunks don't load at all.
Our console reads:
**[Server] Server thread/INFO [STDOUT]: [com.hbm.handler.RadiationSystemNT:updateRadiation:413]: Rads took too long: 310
[Server] Server thread/INFO [STDOUT]: [com.hbm.handler.RadiationSystemNT:updateRadiation:413]: Rads took too long: 84
[Server] Server thread/INFO [STDOUT]: [com.hbm.handler.RadiationSystemNT:updateRadiation:413]: Rads took too long: 51**
and so on...

We have also tried disabling the new config setting. But without it, the radiation spreads until the whole continent is dead. It won't stop, it converts grass to dead grass which in turn releases further radiation and converting more grass into dead grass. 
I don't remember the radiation being so extreme in previous versions.

We also don't want to enable automatic radiation cleanup because then our custom wasteland biomes would vanish instantly.

**Comment by Drillgon200** [comment]
What's the mod version number? Disabling it should make it exactly the same as the radiation in previous versions.

**Comment by Drillgon200** [comment]
Alright, I've improved my radiation pocket generation code quite a bit, so hopefully it'll be considerably less laggy next update. What are you doing to generate that much radiation anyway?

**Comment by Shirhix** [comment]
We have made a wasteland biome using biometweaker. 
screenshot: https://imgur.com/a/6qkYOLu

on the left there is a glowing wasteland with glowing mycelium and glowing mushrooms that cause radiation.
Here is an example of what happens when I stand in this biome for a while: https://imgur.com/a/BOKrw4k
