### ISSUE TITLE
Steam turbine bug

### ISSUE THREAD

**Issue by abel1502** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#99]
When configuring the steam turbine (hbm:machine_turbine) to use super dense steam, the icon color changes correctly, but the internal reservoir is still set to steam and won't accept the super dense one.

**Comment by Drillgon200** [comment]
I found an issue with it not accepting stacks of fluid tanks, but I can't replicate it not being able to accept super dense steam at all.

**Comment by abel1502** [comment]
I guess then it might be a compatibility issue with some other mod - my candidates BuildCraft, RailCraft, IndustialCraft2 and Industrial Renewal, as those are the only ones that may have steam variants in them. I'll check if there's any other fluid identifier for super dense steam visible in NEI.

(To clarify: the steam itself I get from your nuclear recator, so it's definitely the right kind - unlesd the reactor itself is flawed. And it works correctly stage 1 and 2 steams)

**Comment by abel1502** [comment]
In the meantine, I guess a good workaround on your side would be to check the steam variants via the FluidTypeHandler, rather than exact eqality with the one in the registry. Also, to make your life easier, I suggest you to store the booleat fluid properties in a bitmask instead of actual separate booleans. Then you won't have to add a `, false` to all liquids with every new property, and will just need to add something like ` IS_STEAM_SUPERHOT` to several places.

EDIT: Or, rather, add just one extra field to FluidProperties, which would contain a reference to its corresponding fluid from hbm - that way you'll have a way to resolve all alternate fluids to their hbm counterparts

**Comment by Drillgon200** [comment]
That's not how it's supposed to work. What's supposed to happen is that the first mod that registers a fluid gets to be the fluid used, and every other mod automatically grabs that fluid as the reference. I don't think the fluid type handler is the right way to solve this. At most, I would change the reference check to a name check instead. Can you tell me the mod version number as well as upload a log? Also is this pack available anywhere for testing?

**Comment by abel1502** [comment]
I'm using hbm 1.4.4a, but actually, while reproducing the problem for the log, I found my problem: there was several milibuckets of steam left in the turbine, and I didn't notice it... Sorry for wasting your time on this one, issue closed.

**Comment by Drillgon200** [comment]
Oh, alright. Honestly I should probably clear the tank when the type is set, so I don't think it was a waste of time.
